name = "rmq"
version = "0.1.0"
defaultTargets = ["RMQ"]

[[lean_lib]]
name = "RMQ"

[[lean_lib]]
name = "RMQHub"

[[lean_lib]]
name = "RMQRankSelect"

[[lean_lib]]
name = "RMQBPNavigation"

[[lean_lib]]
name = "RMQArchive"

[[lean_lib]]
name = "RMQExamples"
