import RMQ.Core.SuccinctClose

/-!
# Succinct close compatibility root

Compatibility import root for the old `RMQ.SuccinctCloseProposal` namespace.
New code should import `RMQ.Core.SuccinctClose` and use `RMQ.SuccinctClose`.
-/

namespace RMQ
namespace SuccinctCloseProposal

export SuccinctClose (
  BlockLocalBPCloseLCASpec closeToInorder closeToInorder_eq_of_bpCloseOfInorder?
  bpCloseOfInorder?_le_of_le bpCloseOfInorder?_lt_of_lt
  endpoint_closes_ordered_of_query_span answerClose_between_endpoint_closes
  answerClose_prefix_between_endpoint_prefixes endpoint_prefix_range_count_pos
  answerClose_prefix_mem_endpoint_prefix_range densePairSlot densePairSlot_lt
  densePairSlot_div densePairSlot_mod concreteBlockLocalBPCloseLCAEntry?
  concreteBlockLocalBPCloseLCAEntries concreteBlockLocalBPCloseLCAEntries_length
  concreteBlockLocalBPCloseLCAEntries_mem_bound
  concreteBlockLocalBPCloseLCAEntries_spec blockLocalBPCloseLCA_read_exact
  BlockLocalBPCloseLCATable denseAllCloseBPCloseLCATable
  denseAllCloseBPCloseLCATable_profile denseAllCloseBPCloseLCAOverhead
  denseAllCloseBPCloseLCATable_payload_length_of_shapeOfSize not_littleOLinear_square
  denseAllCloseBPCloseLCAOverhead_not_littleO blockOfClose blockStartOf
  blockStartOf_succ blockStartOf_mono blockStartOf_blockOfClose_le
  close_lt_blockStartOf_blockOfClose_add blockPairMacroBlockerShape
  blockPairMacroDirectory_not_sufficient endpointSummaryBlockKey
  endpointSummaryBlockMacroDirectory_not_sufficient BlockCodeTable BlockMicroCodebook
  PayloadLiveBlockMicroCodebook emptyBlockCodeTable emptyOptionNatTable
  emptyPayloadLiveBlockMicroCodebook
  emptyPayloadLiveBlockMicroCodebook_lcaCloseCosted_erase MacroMicroBPCloseLCADirectory
  PayloadLiveMacroMicroBPCloseLCADirectory
  PayloadLiveGuardedBPEndpointFringeMacroMicroBPCloseLCADirectory
  concreteGuardedBPEndpointFringeMacroMicroBPCloseLCADirectory
  concreteGuardedBPEndpointFringeMacroMicroBPCloseLCADirectory_profile
  guardedEndpointFringeMacroMicroOverhead_littleO
  concreteGuardedBPEndpointFringeMacroMicroBPCloseLCADirectory_sampled_profile
  concreteBPEndpointFringeRangeMacro concreteBPEndpointFringeRangeMacro_profile
  concreteBPEndpointFringeRangeMacro_sampled_profile
  concreteBPEndpointFringeRangeMacro_sampled_query_profile
  concreteBPEndpointFringeRangeMacro_read_words_length_le_machine
  PayloadLiveBPEndpointFringeRangeMacro endpointFringeSlot
  endpointLeftFringeRangeOfSlot endpointRightFringeRangeOfSlot endpointLeftFringeRanges
  endpointLeftFringeRanges_length endpointFringeSlot_lt endpointFringeSlot_div
  endpointFringeSlot_mod endpointRightFringeRanges endpointRightFringeRanges_length
  endpointLeftFringeRanges_get?_of_close_bounds
  endpointRightFringeRanges_get?_of_close_bounds
  endpointLeftFringeMinExcessEntries_get?_of_close_bounds
  endpointLeftFringeArgMinEntries_get?_of_close_bounds
  endpointRightFringeMinExcessEntries_get?_of_close_bounds
  endpointRightFringeArgMinEntries_get?_of_close_bounds interiorBlockPairRangeOfSlot
  interiorBlockPairRanges interiorBlockPairRanges_length
  interiorBlockPairRanges_get?_of_gap_bounds
  interiorBlockPairRangeMinExcessEntries_get?_of_gap_bounds
  interiorBlockPairRangeArgMinEntries_get?_of_gap_bounds
  bpRelativeRmmCandidateMerge_exact_of_left_fringe_leftmost
  bpRelativeRmmCandidateMerge_exact_of_right_fringe_leftmost
  bpRelativeRmmCandidateMerge_exact_of_middle_leftmost
  bpRelativeRmmCandidateMerge_exact_of_query_semantics
  bpRelativeRmmCandidateMerge_exact bpCandidateBetter bpCandidateMerge?
  bpCandidateMerge3? bpCandidateClose? bpCandidateBetter_eq_left_of_fst_le
  bpCandidateBetter_eq_right_of_fst_lt bpCandidateMerge?_some_left_of_fst_le
  bpCandidateMerge?_some_right_of_fst_lt bpCandidateMerge3?_eq_some_left_of_fst_le
  bpCandidateMerge3?_eq_some_middle_of_fst_lt_left_le_right
  bpCandidateMerge3?_eq_some_right_of_fst_lt_left_middle bpCandidateMerge?_argmin_pair
  bpCandidateMerge?_adjacentRangeWitness bpCandidateMerge3?_threeAdjacentRangeWitness
  bpCandidateMerge?_bpSparseTwoSpanArgMinBlock
  bpCandidateMerge?_bpSparseLogSpanArgMinBlock
  PayloadLiveBPRelativeRmmInteriorDirectory proofOnlyBPRelativeRmmInteriorDirectory
  payloadLiveBPRelativeRmmInteriorDirectory_profile_allows_proof_only_oracle
  canonicalBPRelativeSummary_block_div_lt_superCount
  concreteBPRelativeRmmInteriorLocalTable concreteBPRelativeRmmInteriorGlobalTable
  concreteBPRelativeRmmInteriorLocalTable_payload_le_budget_of_size_ge
  concreteBPRelativeRmmInteriorGlobalTable_payload_le_budget_of_size_ge
  concreteBPRelativeRmmInteriorDirectoryPayloadLength
  concreteBPRelativeRmmInteriorDirectory concreteBPRelativeRmmInteriorDirectory_profile
  concreteBPRelativeMinMaxArgSummaryTable_canonical_interior_scan_not_constant
  bpGlobalSparseCellSlot bpGlobalSparseCellBlock bpGlobalSparseBlockEntries
  bpGlobalSparseCellSlot_lt bpGlobalSparseCellSlot_div bpGlobalSparseCellSlot_mod
  bpGlobalSparseBlockEntries_get?_of_valid bpGlobalSparseCellBlock_valid_eq
  bpGlobalSparseCellBlock_lt_width bpGlobalSparseBlockEntries_mem_bound
  PayloadLiveBPGlobalSparseBlockTable bpLocalSparseOffsetEntries_length
  concreteBPLocalSparseOffsetTable bpGlobalSparseBlockEntries_length
  concreteBPGlobalSparseBlockTable bpTwoLevelCrossMacroCandidateCosted
  bpTwoLevelAdjacentMacroCandidateCosted
  bpTwoLevelAdjacentMacroCandidateCosted_cost_le_twenty
  bpTwoLevelAdjacentMacroCandidateCosted_erase_exact
  bpTwoLevelLeftMiddleMacroCandidateCosted
  bpTwoLevelLeftMiddleMacroCandidateCosted_cost_le_twenty
  bpTwoLevelLeftMiddleMacroCandidateCosted_erase_exact
  bpTwoLevelCrossMacroCandidateCosted_cost_le_thirty
  bpTwoLevelCrossMacroCandidateCosted_erase_exact bpTwoLevelInteriorCandidateCosted
  bpTwoLevelInteriorCandidateCosted_cost_le_thirty bpTwoLevelInteriorCandidateWordsRead
  bpTwoLevelInteriorCandidateWordsRead_length_le_machine
  bpTwoLevelInteriorCandidateCosted_erase_exact
  concreteBPTwoLevelCrossMacroCandidate_profile localSparseOffsetWordRead
  localSparseOffsetWordRead_length_le_machine globalSparseBlockWordRead
  globalSparseBlockWordRead_length_le_machine localSpanCandidateWordsRead
  localSpanCandidateWordsRead_length_le_machine globalSpanCandidateWordsRead
  globalSpanCandidateWordsRead_length_le_machine localTwoSpanCandidateWordsRead
  localTwoSpanCandidateWordsRead_length_le_machine globalTwoSpanCandidateWordsRead
  globalTwoSpanCandidateWordsRead_length_le_machine
  bpTwoLevelAdjacentMacroCandidateWordsRead
  bpTwoLevelAdjacentMacroCandidateWordsRead_length_le_machine
  bpTwoLevelLeftMiddleMacroCandidateWordsRead
  bpTwoLevelLeftMiddleMacroCandidateWordsRead_length_le_machine
  bpTwoLevelCrossMacroCandidateWordsRead
  bpTwoLevelCrossMacroCandidateWordsRead_length_le_machine
  bpRangeArgMinPrefixPosFrom_mem_of_best_and_candidates
  bpRangeArgMinPrefixPos_mem_prefix_range bpPrefixRangeMinExcess_ge_of_all_prefix_ge
  bpPrefixRangeMinExcess_gt_of_all_prefix_gt bpRangeMinExcess_ge_of_all_prefix_ge
  bpRangeMinExcess_gt_of_all_prefix_gt bpPrefixRangeMinExcess_le_length
  bpPrefixRangeMinExcess_le_prefix_of_mem bpEndpointPrefixRangeMinExcess_le_answerClose
  scanWindow_node_representative_spanning_root
  answerClose_eq_root_close_of_spanning_root
  answerClose_prefix_leftmost_min_excess_of_spanning_root
  answerClose_prefix_leftmost_min_excess_of_query
  endpointPrefixRangeWitness_eq_answerClose_of_spanning_root bpLocalSparseCellSlot
  bpLocalSparseCellOffset bpLocalSparseOffsetEntries bpLocalSparseCellSlot_lt
  bpLocalSparseCellSlot_div_perMacro bpLocalSparseCellSlot_mod_perMacro
  bpLocalSparseCellSlot_rem_div bpLocalSparseCellSlot_rem_mod
  bpLocalSparseOffsetEntries_get?_of_valid bpLocalSparseCellOffset_valid_eq
  bpLocalSparseCellOffset_valid_add bpLocalSparseCellOffset_lt_width
  bpLocalSparseOffsetEntries_mem_bound PayloadLiveBPLocalSparseOffsetTable
  bpRangeWitness_eq_of_bpRangeArgMinBlock bpPrefixRangeArgMinPrefixPosFrom
  bpPrefixRangeArgMinPrefixPosFrom_le_length
  bpPrefixRangeArgMinPrefixPosFrom_excess_le_best
  bpPrefixRangeArgMinPrefixPosFrom_excess_le_pos_add
  bpPrefixRangeArgMinPrefixPosFrom_eq_best_of_best_le_all
  bpPrefixRangeArgMinPrefixPosFrom_eq_of_leftmost_min_excess
  bpPrefixRangeArgMinPrefixPos bpPrefixRangeArgMinPrefixPos_le_length
  bpPrefixRangeArgMinPrefixPos_eq_of_leftmost_min_excess
  bpPrefixRangeArgMinPrefixPosFrom_mem_range bpPrefixRangeArgMinPrefixPos_mem_range
  bpPrefixRangeArgMinPrefixPos_excess_le_offset bpPrefixRangeMinExcess
  bpPrefixRangeMinExcess_eq_of_leftmost_min_excess
  bpPrefixRangeWitness_eq_of_leftmost_min_excess
  bpBlockArgMinPrefixPosFrom_eq_prefixRangeArgMinPrefixPosFrom
  bpBlockArgMinPrefixPos_eq_prefixRangeArgMinPrefixPos
  bpBlockArgMinPrefixPos_eq_of_leftmost_min_excess bpBlockArgMinPrefixPos_mem_range
  bpPrefixRangeMinExcessEntries bpPrefixRangeArgMinPrefixPosEntries
  bpPrefixRangeMinExcessEntries_length bpPrefixRangeArgMinPrefixPosEntries_length
  bpPrefixRangeMinExcessEntries_get?_of_ranges_get?
  bpPrefixRangeArgMinPrefixPosEntries_get?_of_ranges_get?
  bpPrefixRangeMinExcessEntries_mem_bound bpPrefixRangeArgMinPrefixPosEntries_mem_bound
  PayloadLiveBPPrefixRangeArgMinWitnessTable concreteBPPrefixRangeArgMinWitnessTable
  bpRelativeSummaryMinCandidate bpRelativeExcessEntry_decode
  bpBlockRelativeMinExcess_decode bpBlockArgMinLocalOffset_decode
  bpBlockArgMinPrefixPos_excess_le_offset bpBlockMinExcess_eq_excess_argMin
  bpSuperblockBaselineEntries_get?_of_lt bpBlockRelativeMinExcessEntries_get?_of_lt
  bpBlockRelativeMaxExcessEntries_get?_of_lt bpBlockArgMinLocalOffsetEntries_get?_of_lt
  bpRangeArgMinPrefixPosFrom_eq_best_of_best_le_all
  bpRangeArgMinPrefixPosFrom_eq_of_leftmost_block_candidate
  bpRangeArgMinPrefixPos_eq_of_leftmost_block_candidate
  bpRangeMinExcess_eq_of_leftmost_block_candidate
  bpRangeWitness_eq_of_leftmost_block_candidate bpBetterArgMinBlock
  bpBetterArgMinBlock_eq_left_of_excess_le bpBetterArgMinBlock_eq_right_of_excess_lt
  bpExcessAt_bpBetterArgMinBlock_le_left bpExcessAt_bpBetterArgMinBlock_le_right
  bpRangeArgMinBlockFrom bpRangeArgMinBlock bpBlockArgMinPrefixPos_bpBetterArgMinBlock
  bpBlockArgMinPrefixPos_bpRangeArgMinBlockFrom
  bpBlockArgMinPrefixPos_bpRangeArgMinBlock_of_pos bpRangeArgMinBlockFrom_mem
  bpRangeArgMinBlock_mem bpRangeArgMinBlockFrom_leftmost bpRangeArgMinBlock_leftmost
  bpSparseTwoSpanArgMinBlock bpSparseTwoSpanArgMinBlock_leftmost
  bpRangeWitness_eq_of_bpSparseTwoSpanArgMinBlock bpSparseLogSpan bpSparseLogSpan_pos
  bpSparseLogSpan_le_self self_le_two_mul_bpSparseLogSpan bpSparseLogSpanArgMinBlock
  bpRangeWitness_eq_of_bpSparseLogSpanArgMinBlock bpExcessAt bpExcessAt_le_length
  bpExcessAt_prefix_nonnegative bpExcessAt_add_close_rank_eq_open_rank_of_le
  bpCode_rankTrue_full bpExcessAt_close_succ_add_inorder_succ_eq_open_rank
  bpExcessAt_node_left_prefix_succ bpExcessAt_node_right_prefix_shift
  bpExcessAt_node_root_close_succ bpExcessAt_node_pos_before_root_close_succ_pos
  bpExcessAt_node_root_close_succ_le_prefix bpExcessAt_node_root_close_succ_lt_before
  natListMinFrom natListMinFrom_le_seed natListMax natListMax_le_of_forall_mem
  bpBlockExcessSamples bpBlockExcessSamples_mem_le_length bpBlockMinExcess
  bpBlockMaxExcess bpBlockMinExcess_le_length bpBlockMaxExcess_le_length
  bpBlockArgMinPrefixPosFrom bpBlockArgMinPrefixPosFrom_le_length
  bpBlockArgMinPrefixPos bpBlockArgMinPrefixPos_le_length bpBlockMinExcessEntries
  bpBlockMaxExcessEntries bpBlockArgMinPrefixPosEntries bpBlockMinExcessEntries_length
  bpBlockMaxExcessEntries_length bpBlockArgMinPrefixPosEntries_length
  bpBlockMinExcessEntries_mem_bound bpBlockMaxExcessEntries_mem_bound
  bpBlockArgMinPrefixPosEntries_mem_bound PayloadLiveBPRangeMinMaxSummaryTable
  concreteBPRangeMinMaxSummaryTable concreteBPRangeMinMaxSummaryTable_profile
  concreteBPRangeMinMaxSummaryTable_sampled_profile
  concreteBPRangeMinMaxSummaryTable_read_words_length_le_machine
  compactBPCloseSummaryPayloadOverhead compactBPCloseSummaryPayloadOverhead_littleO
  concreteBPRangeMinMaxSummaryTable_compact_summary_profile
  PayloadLiveBPRangeMinMaxArgSummaryTable concreteBPRangeMinMaxArgSummaryTable
  concreteBPRangeMinMaxArgSummaryTable_profile
  concreteBPRangeMinMaxArgSummaryTable_sampled_profile
  concreteBPRangeMinMaxArgSummaryTable_read_words_length_le_machine
  bpBetterArgMinPrefixPos bpBetterArgMinPrefixPos_le_length
  bpExcessAt_bpBetterArgMinPrefixPos_le_left
  bpExcessAt_bpBetterArgMinPrefixPos_le_right
  bpBetterArgMinPrefixPos_eq_left_of_excess_le
  bpBetterArgMinPrefixPos_eq_right_of_excess_lt bpRangeArgMinPrefixPosFrom
  bpRangeArgMinPrefixPosFrom_le_length bpRangeArgMinPrefixPos
  bpRangeArgMinPrefixPos_le_length bpRangeMinExcess bpRangeMinExcess_le_length
  bpRangeMinExcessEntries bpRangeArgMinPrefixPosEntries bpRangeMinExcessEntries_length
  bpRangeArgMinPrefixPosEntries_length bpRangeMinExcessEntries_get?_of_ranges_get?
  bpRangeArgMinPrefixPosEntries_get?_of_ranges_get? bpRangeMinExcessEntries_mem_bound
  bpRangeArgMinPrefixPosEntries_mem_bound PayloadLiveBPRangeArgMinWitnessTable
  concreteBPRangeArgMinWitnessTable concreteBPRangeArgMinWitnessTable_profile
  concreteBPRangeArgMinWitnessTable_sampled_profile
  concreteBPRangeArgMinWitnessTable_read_words_length_le_machine blockPairRangeSlot
  blockPairRangeOfSlot blockPairRanges blockPairRanges_length blockPairRangeSlot_lt
  blockPairRangeSlot_div blockPairRangeSlot_mod blockPairRanges_get?_of_ordered_bounds
  PayloadLiveBPBlockPairRangeWitnessMacro concreteBPBlockPairRangeWitnessMacro
  concreteBPBlockPairRangeWitnessMacro_profile
  concreteBPBlockPairRangeWitnessMacro_sampled_profile
  concreteBPBlockPairRangeWitnessMacro_read_words_length_le_machine
  PayloadLiveRelativeRmmBPCloseMacro PayloadLiveCompactEndpointRelativeRmmBPCloseMacro
  concretePayloadLiveCompactEndpointRelativeRmmBPCloseMacroPayloadLength
  concretePayloadLiveCompactEndpointRelativeRmmBPCloseMacroOverhead
  concretePayloadLiveCompactEndpointRelativeRmmBPCloseMacro
  concretePayloadLiveCompactEndpointRelativeRmmBPCloseMacro_profile
  ConcreteCompactBPCloseLCADirectory concreteCompactBPCloseLCADirectory
  concreteCompactBPCloseLCADirectory_profile_of_size_ge
  concreteCompactBPCloseLCADirectory_profile
  payloadLiveRelativeRmmBPCloseMacroOfInterior
  payloadLiveRelativeRmmBPCloseMacroOfInterior_profile
  concretePayloadLiveRelativeRmmBPCloseMacroPayloadLength
  concretePayloadLiveRelativeRmmBPCloseMacroOverhead
  concretePayloadLiveRelativeRmmBPCloseMacro
  concretePayloadLiveRelativeRmmBPCloseMacro_profile payloadWordReadOfGet?
  payloadWordReadOfGet?_length_le endpointLeftLocalFringeSlot
  endpointRightLocalFringeSlot endpointLocalFringeRangeOfSlot endpointLocalFringeRanges
  endpointLocalFringeRanges_length endpointLocalFringeRanges_get?_left
  endpointLocalFringeRanges_get?_right endpointLocalFringeMinExcessEntries_get?_left
  endpointLocalFringeArgMinEntries_get?_left
  endpointLocalFringeMinExcessEntries_get?_right
  endpointLocalFringeArgMinEntries_get?_right PayloadLiveBlockEndpointFringeCodebook
  concreteEndpointFringeMinEntries concreteEndpointFringeArgEntries
  concreteEndpointFringeMinEntries_length concreteEndpointFringeArgEntries_length
  concreteEndpointFringeMinTable concreteEndpointFringeArgTable
  concreteEndpointFringeMinTable_payload_length
  concreteEndpointFringeArgTable_payload_length
  concretePayloadLiveBlockEndpointFringeCodebookTableOverhead
  concretePayloadLiveBlockEndpointFringeCodebookPayloadLength
  concretePayloadLiveBlockEndpointFringeCodebook
  concretePayloadLiveBlockEndpointFringeCodebook_profile
  concretePayloadLiveBlockEndpointFringeCodebook_canonical
  concretePayloadLiveBlockEndpointFringeCodebook_canonical_profile
  compactBPCloseOverhead compactBPCloseOverhead_littleO concreteCompactBPCloseQueryCost
  concreteCompactBPCloseQueryCostWithRankSeed bpCodeWordReadsAt
  bpCodeWordReadsAt_length_le_machine list_take_add_eq_take_append_drop_take
  flatten_bpCodeWordReadsAt_eq_take_drop localBPBlockWordsRead localBPWindowBase
  localBPWindowBits localBPWindowBits_eq_flatten_localBPBlockWordsRead
  localBPWindowGet? localBPWindowBits_length_le
  zeroBlockSameBlock_does_not_imply_localBPWindowCoverage
  localBPWindowGet?_eq_bpCode_get? localBPBlockWordsRead_get?_eq_bpCode_get?
  localBPWindowBits_end_le_bpCode_length localBPWindowBase_le_blockStart
  localBPWindow_block_end_le_four_words localBPWindowBits_covers_of_le_width
  localBPSeedExcess localBPSeedFromRankFalse rankPrefix_true_add_false_eq_of_le_length
  localBPSeedFromRankFalse_eq_localBPSeedExcess localBPSeedFromRankFalseCosted
  localBPSeedFromRankFalseCosted_cost_le
  localBPSeedFromRankFalseCosted_eq_localBPSeedExcess localBPSeedFromRankCloseCosted
  localBPSeedFromRankCloseCosted_cost_le
  localBPSeedFromRankCloseCosted_eq_localBPSeedExcess
  localBPWindowBits_alone_does_not_determine_base_excess localBPSeededExcessAt
  localBPSeededExcessAt_eq_bpExcessAt localBPSeededBetterPrefixPos
  localBPSeededBetterPrefixPos_bounds
  localBPSeededBetterPrefixPos_eq_bpBetterArgMinPrefixPos
  localBPSeededPrefixRangeArgMinPrefixPosFrom
  localBPSeededPrefixRangeArgMinPrefixPosFrom_bounds
  localBPSeededPrefixRangeArgMinPrefixPosFrom_eq_bpPrefixRangeArgMinPrefixPosFrom
  localBPSeededPrefixRangeArgMinPrefixPos localBPSeededPrefixRangeMinExcess
  localBPSeededPrefixRangeArgMinPrefixPos_bounds_of_pos
  localBPSeededPrefixRangeArgMinPrefixPos_eq_bpPrefixRangeArgMinPrefixPos_of_pos
  localBPSeededPrefixRangeMinExcess_eq_bpPrefixRangeMinExcess_of_pos
  localBPLeftFringeCandidateSeededCosted localBPRightFringeCandidateSeededCosted
  localBPBlockWordsRead_length_le_machine
  localBPLeftFringeCandidateSeededCosted_cost_le
  localBPRightFringeCandidateSeededCosted_cost_le localBPSameBlockCloseSeededCosted
  localBPSameBlockCloseDecodedCosted localBPSameBlockCloseDecodedCostedWithRankSeed
  localBPSameBlockCloseSeededCosted_cost_le localBPSameBlockCloseDecodedCosted_cost_le
  localBPSameBlockCloseDecodedCostedWithRankSeed_cost_le
  localBPSameBlockCloseSeededCosted_eq_semantic
  localBPSameBlockCloseDecodedCosted_eq_semantic
  localBPSameBlockCloseDecodedCostedWithRankSeed_eq_semantic
  localBPSameBlockClosePrefixRange_exact localBPSameBlockCloseDecodedCosted_exact
  localBPSameBlockCloseDecodedCostedWithRankSeed_exact
  localBPSameBlockCloseDecodedCosted_exact_of_query_same_block
  localBPSameBlockCloseDecodedCostedWithRankSeed_exact_of_query_same_block
  localBPSameBlockCloseCosted localBPSameBlockCloseCosted_cost_le
  localBPSameBlockCloseCosted_exact localBPLeftFringeCandidateCosted
  localBPRightFringeCandidateCosted localBPLeftFringeCandidateSeededCosted_eq_semantic
  localBPRightFringeCandidateSeededCosted_eq_semantic
  localBPLeftFringeCandidateCosted_cost_le localBPRightFringeCandidateCosted_cost_le
  bpRelativeRmmCandidateMerge_exact_of_query_semantics_no_block_bounds
  canonicalBPRelativeSummaryBlockCountRaw_upper_cover
  canonicalBPRelativeSummary_blockOfClose_le_blockCount_of_active
  canonicalBPRelativeSummary_blockOfClose_le_blockCount_of_large
  cartesianShape_shapeOfSize_self PayloadLiveRelativeRmmMacroMicroBPCloseLCADirectory
  relativeRmmMacroMicroBPCloseLCAOverhead
  relativeRmmMacroMicroBPCloseLCAOverhead_littleO
  relativeRmmMacroMicroBPCloseLCADirectory_profile
  denseFallbackPayloadLiveMacroMicroBPCloseLCADirectory
  denseFallbackPayloadLiveMacroMicroBPCloseLCADirectory_profile
  payloadLiveMacroMicroBPCloseLCAOverhead
  payloadLiveMacroMicroBPCloseLCAOverhead_littleO PayloadLiveMacroMicroBPCloseLCAFamily
  payloadLiveMacroMicroBPCloseNavigationOverhead
  payloadLiveMacroMicroBPCloseNavigationOverhead_littleO
  PayloadLiveMacroMicroBPCloseNavigationFamily rankPrefix_le_rankPrefix_add_distance
  bpExcessAt_le_bpExcessAt_add_distance_right
  bpExcessAt_le_bpExcessAt_add_distance_left bpSuperblockStartBlock bpSuperblockSpan
  bpSuperblockStartPos bpSuperblockStartBlock_le
  block_lt_bpSuperblockStartBlock_add_blocksPerSuper
  blockStart_add_offset_le_blockCount_mul bpSuperblockStartPos_le_blockStart_add_offset
  blockStart_add_offset_le_bpSuperblockEnd bpBlockSample_excess_le_baseline_add_span
  bpBlockSample_baseline_le_excess_add_span natListMinFrom_le_of_mem
  le_natListMinFrom_add_of_forall_mem le_natListMax_of_mem
  bpBlockExcessSamples_offset_mem bpBlockMinExcess_le_baseline_add_span
  bpBlockMinExcess_baseline_le_add_span bpBlockMaxExcess_le_baseline_add_span
  bpBlockMaxExcess_baseline_le_add_span bpRelativeExcessEntry
  bpRelativeExcessEntry_le_two_span bpBlockRelativeMinExcess bpBlockRelativeMaxExcess
  bpBlockArgMinLocalOffset bpBlockArgMinPrefixPosFrom_le_start_add
  bpBlockArgMinLocalOffset_le_blockSize bpSuperblockBaselineEntries
  bpBlockRelativeMinExcessEntries bpBlockRelativeMaxExcessEntries
  bpBlockArgMinLocalOffsetEntries bpSuperblockBaselineEntries_length
  bpBlockRelativeMinExcessEntries_length bpBlockRelativeMaxExcessEntries_length
  bpBlockArgMinLocalOffsetEntries_length bpSuperblockBaselineEntries_mem_bound
  bpBlockRelativeMinExcessEntries_mem_bound bpBlockRelativeMaxExcessEntries_mem_bound
  bpBlockArgMinLocalOffsetEntries_mem_bound relativeBPCloseSummaryPayloadOverhead
  relativeBPCloseSummaryPayloadOverhead_littleO
  relativeBPCloseSummaryPayloadOverhead_le_compact
  PayloadLiveBPRelativeMinMaxArgSummaryTable concreteBPRelativeMinMaxArgSummaryTable
  concreteBPRelativeMinMaxArgSummaryTable_profile
  concreteBPRelativeMinMaxArgSummaryTable_relative_payload_profile
  concreteBPRelativeMinMaxArgSummaryTable_compact_payload_profile
  concreteBPRelativeMinMaxArgSummaryTable_read_words_length_le_machine
  canonicalBPRelativeSummaryBase canonicalBPRelativeSummaryBlockSizeRaw
  canonicalBPRelativeSummaryBlocksPerSuperRaw canonicalBPRelativeSummaryBlockCountRaw
  canonicalBPRelativeSummarySuperCountRaw canonicalBPRelativeSummarySuperWidth
  canonicalBPRelativeSummaryRelativeWidthRaw canonicalBPRelativeSummarySuperSlots
  canonicalBPRelativeSummaryBlockSlots canonicalBPRelativeMinMaxArgSummaryTableActive
  canonicalBPRelativeSummaryBlockSize canonicalBPRelativeSummaryBlocksPerSuper
  canonicalBPRelativeSummaryBlockCount canonicalBPRelativeSummarySuperCount
  canonicalBPRelativeSummaryRelativeWidth canonicalBPRelativeSummaryLargeRegime
  canonicalBPRelativeSummary_large_parts natLog2_ge_of_pow_le
  natLog2_succ_le_of_pos_lt_pow nat_succ_square_le_two_pow_of_six_le
  nat_log2_succ_square_le_self_of_log2_ge_six
  canonicalBPRelativeSummaryBase_le_blockCountRaw_of_size_ge
  canonicalBPRelativeSummaryBase_ge_128_of_size_ge
  canonicalBPRelativeSummaryBase_le_superWidth_of_size_pos
  canonicalBPRelativeSummaryBlockSize_le_two_machine_of_size_pos
  canonicalBPRelativeSummarySuperWidth_le_eight_base_of_size_pos
  four_mul_square_lt_two_pow_two_log_succ_add_three
  canonicalBPRelativeSummarySpanRaw_width_bound
  canonicalBPRelativeSummaryBlockSizeRaw_width_bound
  canonicalBPRelativeSummaryRelativeWidthRaw_le_base_of_base_ge_128
  canonicalBPRelativeSummaryLargeRegime_of_size_ge
  canonicalBPRelativeMinMaxArgSummaryTableActive_of_large
  canonicalBPRelativeSummary_blocksPerSuper_pos canonicalBPRelativeSummary_cover
  canonicalBPRelativeSummary_superWidth_bound
  canonicalBPRelativeSummary_relativeWidth_bound
  canonicalBPRelativeSummary_argWidth_bound
  canonicalBPRelativeSummary_superPayload_bound
  canonicalBPRelativeSummary_blockPayload_bound
  canonicalBPRelativeSummary_superWidth_machine
  canonicalBPRelativeSummary_relativeWidth_machine
  concreteBPRelativeMinMaxArgSummaryTable_canonical
  concreteBPRelativeMinMaxArgSummaryTable_canonical_compact_payload_profile
  concreteBPRelativeMinMaxArgSummaryTable_canonical_compact_payload_profile_of_large
  canonicalBPRelativeSummaryBlockSizeRaw_pos
  canonicalBPRelativeSummaryBlockSize_pos_of_active
  canonicalBPRelativeSummaryBlockSize_pos_of_large
  canonicalBPRelativeSummaryBlockSize_pos_of_size_ge
  canonicalBPRelativeSummaryBlocksPerSuperRaw_pos
  canonicalBPRelativeSummaryBlockCountRaw_mul_blockSizeRaw_le_bpCode_length
  canonicalBPRelativeSummaryBlockCountRaw_pos_of_large
  canonicalBPRelativeSummaryBlockCountRaw_le_bpCode_length
  canonicalBPRelativeSummaryBlockCount_le_bpCode_length
  canonicalBPRelativeSummaryRelativeWidthRaw_machine_of_large
  concreteBPRelativeRmmInteriorLocalOffsetSlots
  concreteBPRelativeRmmInteriorGlobalMacroSlots concreteBPRelativeRmmInteriorNodeSlots
  concreteBPRelativeRmmInteriorTopSlots concreteBPRelativeRmmInteriorQueryCost
  concreteBPRelativeRmmInteriorMacroSize concreteBPRelativeRmmInteriorMacroCount
  concreteBPRelativeRmmInteriorOffsetWidth concreteBPRelativeRmmInteriorLevelCount
  concreteBPRelativeRmmInteriorGlobalLevelCount concreteBPRelativeRmmInteriorBlockWidth
  concreteBPRelativeRmmInteriorMacroSize_pos
  concreteBPRelativeRmmInteriorOffsetWidth_capacity
  concreteBPRelativeRmmInteriorBlockWidth_capacity
  concreteBPRelativeRmmInteriorGlobalLevelCount_capacity
  nat_succ_cube_le_two_pow_of_128_le
  concreteBPRelativeRmmInteriorMacroSize_le_blockCount_of_size_ge
  concreteBPRelativeRmmInteriorMacroCover_le_two_blockCount_of_size_ge
  concreteBPRelativeRmmInteriorOffsetWidth_le_five_logBase
  concreteBPRelativeRmmInteriorBlockWidth_le_base_of_size_ge
  concreteBPRelativeRmmInteriorGlobalLevelCount_le_base_succ_of_size_ge
  concreteBPRelativeRmmInteriorOverhead concreteBPRelativeRmmInteriorOverhead_littleO
  concreteBPRelativeRmmInteriorDirectory_parameter_profile_of_large
  concreteBPRelativeRmmInteriorDirectory_parameter_profile_of_size_ge
  concreteBPRelativeRmmInteriorDirectory_twoLevel_budget_profile_of_size_ge
)

namespace BlockCodeTable

export SuccinctClose.BlockCodeTable (
  payload codeAt codeCosted payload_length codeCosted_cost codeCosted_cost_le_one
  codeCosted_erase codeCosted_exact_of_codeAt codeAt_lt codeAt_exists_of_lt profile
  ofEntries ofEntries_profile
)

end BlockCodeTable

namespace BlockLocalBPCloseLCATable

export SuccinctClose.BlockLocalBPCloseLCATable (
  payload lcaCloseCosted payload_length lcaCloseCosted_cost lcaCloseCosted_cost_le_one
  lcaCloseCosted_exact profile ofEntries concrete ofEntries_profile concrete_profile
)

end BlockLocalBPCloseLCATable

namespace BlockMicroCodebook

export SuccinctClose.BlockMicroCodebook (
  tableForBlock lcaCloseCostedAtBlock lcaCloseCosted payload_length
  lcaCloseCostedAtBlock_cost lcaCloseCostedAtBlock_cost_le_one
  lcaCloseCosted_cost_le_one lcaCloseCostedAtBlock_exact
  lcaCloseCosted_exact_of_left_block profile
)

end BlockMicroCodebook

namespace ConcreteCompactBPCloseLCADirectory

export SuccinctClose.ConcreteCompactBPCloseLCADirectory (
  payloadWordsRead crossBlockCloseCosted crossBlockCloseCostedWithRankSeed
  lcaCloseCosted lcaCloseCostedWithRankSeed
  lcaCloseCostedWithRankSeed_eq_positive_dispatch
  lcaCloseCostedWithRankSeed_eq_positive_dispatch_of_size_ge
  crossBlockCloseCosted_cost_le crossBlockCloseCostedWithRankSeed_cost_le
  lcaCloseCosted_cost_le lcaCloseCostedWithRankSeed_cost_le
  crossBlockCloseCosted_erase_decoded crossBlockCloseCostedWithRankSeed_erase_decoded
  crossBlockCloseCosted_exact_of_query crossBlockCloseCostedWithRankSeed_exact_of_query
  lcaCloseCosted_exact_of_query lcaCloseCostedWithRankSeed_exact_of_query
  lcaCloseCostedWithRankSeed_exact_of_query_of_size_ge read_words_length_le_machine
)

end ConcreteCompactBPCloseLCADirectory

namespace MacroMicroBPCloseLCADirectory

export SuccinctClose.MacroMicroBPCloseLCADirectory (
  payload lcaCloseCosted payload_length lcaCloseCosted_cost_le lcaCloseCosted_exact
  profile
)

end MacroMicroBPCloseLCADirectory

namespace PayloadLiveBPBlockPairRangeWitnessMacro

export SuccinctClose.PayloadLiveBPBlockPairRangeWitnessMacro (
  payload rangeIndex lcaCloseCosted payload_length lcaCloseCosted_cost_le_two
  lcaCloseCosted_erase lcaCloseCosted_exact_of_prefix_pos read_words_length_le_machine
  profile
)

end PayloadLiveBPBlockPairRangeWitnessMacro

namespace PayloadLiveBPEndpointFringeRangeMacro

export SuccinctClose.PayloadLiveBPEndpointFringeRangeMacro (
  payload interiorIndex interiorWitnessCosted lcaCloseCosted payload_length
  interiorWitnessCosted_cost_le_two lcaCloseCosted_cost_le_six lcaCloseCosted_erase
  lcaCloseCosted_exact_of_merged_candidate
  lcaCloseCosted_exact_of_decoded_merged_candidate
  lcaCloseCosted_exact_of_left_fringe_leftmost
  lcaCloseCosted_exact_of_decoded_right_fringe_candidate
  lcaCloseCosted_exact_of_decoded_middle_candidate
  lcaCloseCosted_exact_of_spanning_root_left_fringe
  lcaCloseCosted_exact_of_spanning_root_right_fringe
  lcaCloseCosted_exact_of_query_semantics_cross_block
  lcaCloseCosted_exact_of_query_cross_block
  lcaCloseCosted_exact_of_spanning_root_cross_block read_words_length_le_machine
  profile profile_cross_block_exact
)

end PayloadLiveBPEndpointFringeRangeMacro

namespace PayloadLiveBPGlobalSparseBlockTable

export SuccinctClose.PayloadLiveBPGlobalSparseBlockTable (
  payload payload_length readBlockCosted readBlockCosted_cost_le_one
  readBlockCosted_erase_of_valid read_word_length_le_machine spanCandidateCosted
  spanCandidateCosted_cost_le_five spanCandidateCosted_erase_exact
  twoSpanCandidateCosted twoSpanCandidateCosted_cost_le_ten
  twoSpanCandidateCosted_erase_sparse_exact
  twoSpanCandidateCosted_erase_rangeWitness_exact
)

end PayloadLiveBPGlobalSparseBlockTable

namespace PayloadLiveBPLocalSparseOffsetTable

export SuccinctClose.PayloadLiveBPLocalSparseOffsetTable (
  twoSpanCandidateCosted twoSpanCandidateCosted_cost_le_ten
  twoSpanCandidateCosted_erase_sparseLog_exact
  twoSpanCandidateCosted_erase_rangeWitness_exact payload payload_length
  readOffsetCosted readOffsetCosted_cost_le_one readOffsetCosted_erase_of_valid
  read_word_length_le_machine spanCandidateCosted spanCandidateCosted_cost_le_five
  spanCandidateCosted_erase_exact
)

end PayloadLiveBPLocalSparseOffsetTable

namespace PayloadLiveBPPrefixRangeArgMinWitnessTable

export SuccinctClose.PayloadLiveBPPrefixRangeArgMinWitnessTable (
  payload rangeWitnessCosted payload_length rangeWitnessCosted_cost_le_two
  rangeWitnessCosted_erase min_read_word_length_le_machine
  arg_read_word_length_le_machine read_words_length_le_machine profile
)

end PayloadLiveBPPrefixRangeArgMinWitnessTable

namespace PayloadLiveBPRangeArgMinWitnessTable

export SuccinctClose.PayloadLiveBPRangeArgMinWitnessTable (
  payload rangeWitnessCosted rangeCloseCosted payload_length
  rangeWitnessCosted_cost_le_two rangeCloseCosted_cost_le_two rangeWitnessCosted_erase
  rangeCloseCosted_erase rangeCloseCosted_exact_of_prefix_pos
  min_read_word_length_le_machine arg_read_word_length_le_machine
  read_words_length_le_machine payload_length_le_sampled profile
)

end PayloadLiveBPRangeArgMinWitnessTable

namespace PayloadLiveBPRangeMinMaxArgSummaryTable

export SuccinctClose.PayloadLiveBPRangeMinMaxArgSummaryTable (
  payload argMinPrefixPosCosted summaryArgCosted payload_length
  argMinPrefixPosCosted_cost_le_one argMinPrefixPosCosted_erase
  summaryArgCosted_cost_le_three summaryArgCosted_erase arg_read_word_length_le_machine
  read_words_length_le_machine payload_length_le_sampled profile
)

end PayloadLiveBPRangeMinMaxArgSummaryTable

namespace PayloadLiveBPRangeMinMaxSummaryTable

export SuccinctClose.PayloadLiveBPRangeMinMaxSummaryTable (
  payload minExcessCosted maxExcessCosted summaryCosted payload_length
  minExcessCosted_cost_le_one maxExcessCosted_cost_le_one summaryCosted_cost_le_two
  minExcessCosted_erase maxExcessCosted_erase summaryCosted_erase
  minExcess_read_word_length_le_machine maxExcess_read_word_length_le_machine
  summary_read_words_length_le_machine payload_length_le_sampled profile
)

end PayloadLiveBPRangeMinMaxSummaryTable

namespace PayloadLiveBPRelativeMinMaxArgSummaryTable

export SuccinctClose.PayloadLiveBPRelativeMinMaxArgSummaryTable (
  boundedRangeScanCosted boundedRangeScanCosted_cost_le_blockCount
  div_lt_succ_div_of_lt boundedRangeScanCosted_erase_exact scanInteriorDirectory
  scanInteriorDirectory_profile rangeScanFromCosted rangeScanCosted
  rangeScanFromCosted_cost_le rangeScanFromCosted_cost_eq rangeScanCosted_cost_le
  rangeScanCosted_cost_eq rangeScanCosted_no_uniform_constant interiorScanCosted
  interiorScanCosted_cost_eq interiorScanCosted_no_uniform_constant
  rangeScanFromCosted_erase_exact rangeScanCosted_erase_exact
  rangeArgMinBlockCandidateCosted rangeArgMinBlockCandidateCosted_cost_le_four
  rangeArgMinBlockCandidateCosted_erase_exact optionWordList mem_optionWordList
  summaryCandidateWordsRead summaryCandidateWordsRead_length_le_machine
  minCandidateCosted minCandidateCosted_cost_le_four summaryCosted_cost_eq_four
  minCandidateCosted_cost_eq_four summaryCosted_erase_of_bounds
  minCandidateCosted_erase_of_bounds minCandidateCosted_erase_arg_excess_of_bounds
  payload summaryCosted payload_length summaryCosted_cost_le_four summaryCosted_erase
  read_words_length_le_machine profile
)

end PayloadLiveBPRelativeMinMaxArgSummaryTable

namespace PayloadLiveBPRelativeRmmInteriorDirectory

export SuccinctClose.PayloadLiveBPRelativeRmmInteriorDirectory (
  profile
)

end PayloadLiveBPRelativeRmmInteriorDirectory

namespace PayloadLiveBlockEndpointFringeCodebook

export SuccinctClose.PayloadLiveBlockEndpointFringeCodebook (
  payload leftSlot rightSlot witnessCostedAtBlock leftFringeCostedAtBlock
  rightFringeCostedAtBlock leftFringeCosted rightFringeCosted wordsReadAtBlock
  leftWordsReadAtBlock rightWordsReadAtBlock payload_length
  witnessCostedAtBlock_cost_le_three leftFringeCostedAtBlock_cost_le_three
  rightFringeCostedAtBlock_cost_le_three leftFringeCosted_cost_le_three
  rightFringeCosted_cost_le_three leftFringeCostedAtBlock_exact_of_code
  rightFringeCostedAtBlock_exact_of_code leftFringeCostedAtBlock_exact
  rightFringeCostedAtBlock_exact leftFringeCosted_exact rightFringeCosted_exact
  wordsReadAtBlock_length_le_machine read_words_length_le_machine
  leftWordsReadAtBlock_length_le_machine rightWordsReadAtBlock_length_le_machine
  profile
)

end PayloadLiveBlockEndpointFringeCodebook

namespace PayloadLiveBlockMicroCodebook

export SuccinctClose.PayloadLiveBlockMicroCodebook (
  payload lcaCloseCostedAtBlock lcaCloseCosted payload_length
  lcaCloseCostedAtBlock_cost_le_two lcaCloseCosted_cost_le_two
  lcaCloseCostedAtBlock_exact lcaCloseCosted_exact_of_left_block profile
)

end PayloadLiveBlockMicroCodebook

namespace PayloadLiveCompactEndpointRelativeRmmBPCloseMacro

export SuccinctClose.PayloadLiveCompactEndpointRelativeRmmBPCloseMacro (
  payload payloadWordsRead interiorCandidateCosted lcaCloseCosted payload_length
  interiorCandidateCosted_cost_le lcaCloseCosted_cost_le lcaCloseCosted_erase_decoded
  lcaCloseCosted_exact_of_query_cross_block read_words_length_le_machine profile
)

end PayloadLiveCompactEndpointRelativeRmmBPCloseMacro

namespace PayloadLiveGuardedBPEndpointFringeMacroMicroBPCloseLCADirectory

export SuccinctClose.PayloadLiveGuardedBPEndpointFringeMacroMicroBPCloseLCADirectory (
  payload lcaCloseCosted payload_length lcaCloseCosted_cost_le_six lcaCloseCosted_exact
  profile
)

end PayloadLiveGuardedBPEndpointFringeMacroMicroBPCloseLCADirectory

namespace PayloadLiveMacroMicroBPCloseLCADirectory

export SuccinctClose.PayloadLiveMacroMicroBPCloseLCADirectory (
  payload lcaCloseCosted payload_length lcaCloseCosted_cost_le lcaCloseCosted_exact
  profile
)

end PayloadLiveMacroMicroBPCloseLCADirectory

namespace PayloadLiveMacroMicroBPCloseLCAFamily

export SuccinctClose.PayloadLiveMacroMicroBPCloseLCAFamily (
  overhead overhead_littleO Profile profile
)

end PayloadLiveMacroMicroBPCloseLCAFamily

namespace PayloadLiveMacroMicroBPCloseNavigationFamily

export SuccinctClose.PayloadLiveMacroMicroBPCloseNavigationFamily (
  overhead payload selectCloseCosted lcaCloseCosted rankCloseCosted queryBuiltCosted
  overhead_littleO payload_length queryBuiltCosted_cost_le selectCloseCosted_exact
  rankCloseCosted_exact queryBuiltCosted_exact two_n_plus_o_built_query_profile
)

end PayloadLiveMacroMicroBPCloseNavigationFamily

namespace PayloadLiveRelativeRmmBPCloseMacro

export SuccinctClose.PayloadLiveRelativeRmmBPCloseMacro (
  interiorCandidateCosted lcaCloseCosted payload_length interiorCandidateCosted_cost_le
  lcaCloseCosted_cost_le lcaCloseCosted_erase_decoded
  lcaCloseCosted_exact_of_query_semantics_cross_block
  lcaCloseCosted_exact_of_query_cross_block profile
)

end PayloadLiveRelativeRmmBPCloseMacro

namespace PayloadLiveRelativeRmmMacroMicroBPCloseLCADirectory

export SuccinctClose.PayloadLiveRelativeRmmMacroMicroBPCloseLCADirectory (
  payload lcaCloseCosted payload_length lcaCloseCosted_cost_le lcaCloseCosted_exact
  profile
)

end PayloadLiveRelativeRmmMacroMicroBPCloseLCADirectory

end SuccinctCloseProposal
end RMQ
