import RMQ.Core.SuccinctSelect

/-!
# Succinct select compatibility root

Compatibility import root for the old `RMQ.SuccinctSelectProposal` namespace.
New code should import `RMQ.Core.SuccinctSelect` and use `RMQ.SuccinctSelect`.
-/

namespace RMQ
namespace SuccinctSelectProposal

export SuccinctSelect (
  canonicalSparseDenseFalseSelectOverhead canonicalSparseDenseFalseSelectOverhead_littleO
  sparseDenseFalseSelectQueryCost sparseDenseFalseSelectWordBits sparseDenseFalseSelectEll
  sparseDenseFalseSelectSuperStride sparseDenseFalseSelectLocalStride
  sparseDenseFalseSelectSuperLongSpan sparseDenseFalseSelectLocalSparseSpan
  selectPositionsFrom selectPositions selectPositionsFrom_get?_eq_selectFrom
  selectPositions_get?_eq_select selectPositionsFrom_length_eq_rankPrefix_length
  selectPositions_length_eq_rankPrefix_length select_exists_of_lt_rankPrefix
  select_none_of_rankPrefix_length_le denseTwoWordFalseSelectCosted
  denseTwoWordFalseSelectCosted_cost_le_five
  sparseDenseFalseSelectDenseLocalEntryBasePosition denseLocalEntryFalseSelectCosted
  denseLocalEntryFalseSelectCosted_cost_le_five builtRelativeSplitFalseSelectSuperEntry
  builtRelativeSplitFalseSelectSuperEntries
  builtRelativeSplitFalseSelectCompactLocalEntryIsLive
  builtRelativeSplitFalseSelectLocalEntry builtRelativeSplitFalseSelectLocalEntries
  builtRelativeSplitFalseSelectSparseFlagBits
  builtRelativeSplitFalseSelectSparseRelativeEntriesForSlot
  builtRelativeSplitFalseSelectSparseRelativeEntries
  builtRelativeSplitFalseSelectFlagRankWordSize
  builtRelativeSplitFalseSelectFlagRankBlocksPerSuper
  builtRelativeSplitFalseSelectFlagRankBlockWidth
  builtRelativeSplitFalseSelectFlagRankWordSize_pos
  builtRelativeSplitFalseSelectFlagRankBlocksPerSuper_pos
  builtRelativeSplitFalseSelectSparseFlagBits_length_lt_rank_word_pow
  builtRelativeSplitFalseSelectFlagRankBlockSpan_lt_pow
  builtRelativeSplitFalseSelectFlagRankSuperOverhead
  builtRelativeSplitFalseSelectFlagRankBlockOverhead
  builtRelativeSplitFalseSelectFlagRankData
  builtRelativeSplitFalseSelectFlagRankData_profile
  builtRelativeSplitFalseSelectSparseExceptionFlagRankWordSize
  builtRelativeSplitFalseSelectSparseExceptionFlagRankBlocksPerSuper
  builtRelativeSplitFalseSelectSparseExceptionFlagRankBlockWidth
  builtRelativeSplitFalseSelectSparseExceptionFlagRankWordSize_pos
  builtRelativeSplitFalseSelectSparseExceptionFlagRankBlocksPerSuper_pos
  builtRelativeSplitFalseSelectSparseExceptionFlagBits_length_lt_rank_word_pow
  builtRelativeSplitFalseSelectSparseExceptionFlagRankBlockSpan_lt_pow
  builtRelativeSplitFalseSelectSparseExceptionFlagRankSuperOverhead
  builtRelativeSplitFalseSelectSparseExceptionFlagRankBlockOverhead
  builtRelativeSplitFalseSelectSparseExceptionFlagRankData
  builtRelativeSplitFalseSelectSparseExceptionFlagRankData_profile
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankWordSize
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankBlocksPerSuper
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankBlockWidth
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankWordSize_pos
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits_length_le_bpCode_length
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankWordSize_le_machine
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankBlocksPerSuper_pos
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits_length_lt_rank_word_pow
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankBlockSpan_lt_pow
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankSuperOverhead
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankBlockOverhead
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankData
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankData_profile
  builtRelativeSplitFalseSelectSuperEntries_length
  builtRelativeSplitFalseSelectLocalEntries_length
  builtRelativeSplitFalseSelectSuperEntries_get?
  builtRelativeSplitFalseSelectLocalEntries_get?
  builtRelativeSplitFalseSelectSparseFlagBits_length
  builtRelativeSplitFalseSelectSparseFlagBits_get? rankPrefix_succ_eq_of_get?
  builtRelativeSplitFalseSelectSparseRelativeEntriesForSlot_length
  builtRelativeSplitFalseSelectSparseRelativePrefix_length
  builtRelativeSplitFalseSelectSparseExceptionFlagBits_get?
  builtRelativeSplitFalseSelectSparseExceptionRelativePrefix_length
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntries_length
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable_payload_length
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable_payload_le_of_count_bound
  builtRelativeSplitFalseSelectLongFlagRankWordSize
  builtRelativeSplitFalseSelectLongFlagRankBlocksPerSuper
  builtRelativeSplitFalseSelectLongFlagRankBlockWidth
  builtRelativeSplitFalseSelectLongFlagRankWordSize_pos
  builtRelativeSplitFalseSelectLongFlagRankBlocksPerSuper_pos
  builtRelativeSplitFalseSelectLongSuperFlagBits_length_lt_rank_word_pow
  builtRelativeSplitFalseSelectLongFlagRankBlockSpan_lt_pow
  builtRelativeSplitFalseSelectLongFlagRankSuperOverhead
  builtRelativeSplitFalseSelectLongFlagRankBlockOverhead
  builtRelativeSplitFalseSelectLongFlagRankData
  builtRelativeSplitFalseSelectLongFlagRankData_profile
  builtRelativeSplitCompactLongSuperReadCosted
  builtRelativeSplitCompactLongSuperReadCosted_cost_le_five
  builtRelativeSplitCompactLongSuperReadCosted_erase
  compactLongSuperRelativeTable_lookup_exact
  builtRelativeSplitCompactLongSuperReadCosted_lookup_exact
  builtRelativeSplitFalseSelectSparseRelativeEntries_decompose
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntries_decompose
  falseSelectPositions_length falseSelectPositions_mem_le_length
  builtRelativeSplitFalseSelectSparseRelativeEntries_mem_lt_word_pow
  builtRelativeSplitFalseSelectSparseRelativeTable
  builtRelativeSplitFalseSelectSparseRelativeTable_profile
  builtRelativeSplitFalseSelectSparseRelativeTable_payload_length
  fullWidthSparseRelativePayload_not_littleO_of_linear_family
  falseSelectPositions_lookup_exact falseSelectExplicitTable_lookup_exact
  builtRelativeSplitFalseSelectSparseRelativeEntries_lookup_exact
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntries_lookup_exact
  FalseSelectAlignedBitWords falseSelectAlignedBitWords_ofChunks
  falseSelectDenseLocalFirstStart falseSelectDenseLocalSecondStart
  falseSelectDenseLocalSpanEnd falseSelectDenseLocalFirstWord
  falseSelectDenseLocalFirstCount FalseSelectDenseLocalPayloadRoutingFacts
  FalseSelectDenseLocalSpanCertificate
  falseSelectDenseLocalSpanCertificate_of_payload_routing_facts
  denseTwoWordFalseSelectCosted_exact_of_local_span
  denseTwoWordFalseSelectCosted_exact_of_payload_routing_facts
  falseSelectDenseLocalPayloadRoutingFacts_of_selected_span
  falseSelectRelativeOffsetsOrZero_length
  builtRelativeSplitFalseSelectSparseExceptionFlagBits_length
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits_length
  builtRelativeSplitFalseSelectSparseExceptionEffectiveLocalSlotCount_le_full
  builtRelativeSplitFalseSelectSparseExceptionEffectiveLocalSlotCount_le_count
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits_get?
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits_prefix_eq
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntriesForSlot_length
  builtRelativeSplitFalseSelectSuperIsLong_false_span_le
  builtRelativeSplitFalseSelectLocalIsSparseException_true_short
  falseSelect_occurrence_lt_count_of_select falseSelect_exists_of_lt_occurrence_count
  builtRelativeSplitFalseSelectPosition_eq_of_select
  builtRelativeSplitFalseSelectPosition_eq_length_of_count_le
  builtRelativeSplitFalseSelectPosition_mono
  falseSelectOccurrenceCount_pos_of_rectangular_local_slot
  builtRelativeSplitFalseSelectShortSuperLocalEndOccurrence_le_count
  builtRelativeSplitFalseSelectShortSuperLocalEndOccurrence_pos
  builtRelativeSplitFalseSelectShortSuperLocalBase_lt_end_of_base_lt_count
  builtRelativeSplitFalseSelectShortSuperLocalSpan_le_next_gap
  builtRelativeSplitFalseSelect_selected_offset_lt_superLongSpan
  falseSelectRelativeOffsetsOrZero_mem_cases falseSelectRelativeOffsetsOrZero_lookup_exact
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntriesForSlot_mem_lt_width
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntries_mem_lt_width
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable_profile falseSelectSuperSlot
  falseSelectLocalSlotsPerSuper falseSelectOccurrenceCount
  falseSelectOccurrenceCount_eq_size falseSelectCeilDiv
  builtRectangularFalseSelectSuperSlotCount builtRectangularFalseSelectLocalSlotsPerSuper
  builtRectangularFalseSelectLocalSlotCount sparseDenseFalseSelectWordBits_pos
  sparseDenseFalseSelectSuperStride_pos sparseDenseFalseSelectLocalStride_pos
  builtRectangularFalseSelectLocalSlotsPerSuper_pos
  builtRectangularFalseSelectLocalSlotInSuperOfGlobal
  builtRectangularFalseSelectLocalBaseOccurrence
  builtRectangularFalseSelectLocalBaseOccurrence_mod
  builtRectangularFalseSelectLocalBaseOccurrence_lt_superBoundary
  builtRectangularFalseSelectLocalBaseOccurrence_le_next_base falseSelectPositions
  builtRelativeSplitFalseSelectPosition builtRelativeSplitFalseSelectLocalEndOccurrence
  builtRelativeSplitFalseSelectLocalSpan builtRelativeSplitFalseSelectLocalIsSparse
  builtRelativeSplitFalseSelectSuperBaseOccurrence
  builtRelativeSplitFalseSelectSuperEndOccurrence builtRelativeSplitFalseSelectSuperSpan
  builtRelativeSplitFalseSelectSuperIsLong builtRelativeSplitFalseSelectLocalSuperSlot
  builtRelativeSplitFalseSelectShortSuperLocalEndOccurrence
  builtRelativeSplitFalseSelectShortSuperLocalSpan
  builtRelativeSplitFalseSelectShortSuperLocalEndOccurrence_le_next_base
  builtRelativeSplitFalseSelectLocalIsSparseException falseSelectRelativeOffsetsOrZero
  builtRelativeSplitFalseSelectSparseExceptionFlagBits
  builtRelativeSplitFalseSelectSparseExceptionEffectiveLocalSlotCount
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntriesForSlot
  builtRelativeSplitFalseSelectSparseExceptionRelativeEntries
  builtRelativeSplitFalseSelectSparseExceptionRelativeWidth natList_sum_append
  builtRelativeSplitFalseSelectShortSuperLocalSpanSum
  builtRelativeSplitFalseSelectShortSuperLocalSpanSum_prefix_le_position
  falseSelectCeilDiv_mul_ge_of_pos falseSelectCeilDiv_slot_mul_lt
  builtRectangularFalseSelectFinalLocalBaseOccurrence
  builtRelativeSplitFalseSelectShortSuperLocalSpanSum_le_bpCode_length
  builtRelativeSplitFalseSelectSuperBaseOccurrence_lt_count
  builtRelativeSplitFalseSelectSuperEndOccurrence_le_count
  builtRelativeSplitFalseSelectSuperEndOccurrence_pos
  builtRelativeSplitFalseSelectSuperEndOccurrence_le_next_base
  builtRelativeSplitFalseSelectSuperBaseOccurrence_le_next_base
  builtRelativeSplitFalseSelectSuperBase_lt_end_of_base_lt_count
  builtRelativeSplitFalseSelectSuperSpan_le_next_gap
  builtRelativeSplitFalseSelectSparseExceptionCount_wordBits_le_spanSum
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable_payload_le_of_span_product_bound
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable_payload_mul_ell_le_const_spanSum
  sparseExceptionRelativeTableOverhead sparseExceptionRelativeTableOverhead_littleO
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable_payload_le_overhead_of_spanSum_le_bpCode_length
  builtRelativeSplitFalseSelectSparseExceptionRelativeTable_payload_le_overhead
  builtRelativeSplitFalseSelectLongSuperFlagBits
  builtRelativeSplitFalseSelectLongSuperRelativeEntriesForSlot
  builtRelativeSplitFalseSelectLongSuperRelativeEntries
  builtRelativeSplitFalseSelectLongSuperRelativeWidth
  builtRelativeSplitFalseSelectLongSuperFlagBits_get?
  builtRelativeSplitFalseSelectLongSuperRelativeEntriesForSlot_length
  compactLongSuperFlagRank_eq_segmentIndex compactLongSuperRelativeEntries_length
  builtRelativeSplitFalseSelectLongSuperSpanSum
  builtRelativeSplitFalseSelectLongSuperSpanSum_prefix_le_position
  builtRelativeSplitFalseSelectLongSuperSpanSum_le_bpCode_length
  longSuperExceptionCount_mul_superLongSpan_le_spanSum
  builtRelativeSplitFalseSelectLongSuperRelativeEntries_decompose
  builtRelativeSplitFalseSelectLongSuperRelativeEntries_mem_lt_width
  builtRelativeSplitFalseSelectLongSuperRelativeTable
  compactLongSuperRelativeTable_payload_length
  compactLongSuperRelativeTable_payload_mul_ell_le_spanSum
  compactLongSuperRelativeTableOverhead compactLongSuperRelativeTableOverhead_littleO
  compactLongSuperRelativeTable_payload_le_overhead_of_spanSum_le_bpCode_length
  compactLongSuperRelativeTable_payload_le_overhead natLog2_le_log2_of_le
  machineWordBits_mono_le nat_div_succ_le_div_add_one nat_div_add_sub_div_le_add
  nat_div_sub_div_le_sub one_lt_two_pow_of_pos machineWordBits_le_self_of_pos
  lt_two_pow_machineWordBits_of_lt
  builtRelativeSplitFalseSelectSparseExceptionRelativeWidth_le_machine
  natLog2_succ_le_of_pos_lt_pow
  builtRelativeSplitFalseSelectSparseExceptionRelativeWidth_le_four_ell
  nat_succ_square_le_two_pow_of_six_le
  sparseDenseFalseSelectEll_square_le_sixtyFour_wordBits
  builtRelativeSplitFalseSelectSparseException_localStride_mul_width_mul_ell_le_const_wordBits
  falseSelectCeilDiv_mul_le_add falseSelectLocalSlotsPerSuper_mul_localStride_le_add
  nat_succ_square_le_four_mul_two_pow machineWordBits_sq_le_four_mul_self_of_pos
  sparseDenseFalseSelectWordBits_le_two_mul_localStride_mul_ell_sq
  payload_le_logLogCubedSampledDirectoryOverhead_of_mul_wordBits_le
  sparseDenseFalseSelectLocalStride_le_superStride
  builtRectangularFalseSelectLocalSlotCount_mul_localStride_le_const_bpCode_length
  relativeSplitFalseSelectEntryIsMarked relativeSplitFalseSelectEntryBasePosition
  relativeSplitFalseSelectLocalBaseOccurrence relativeSplitFalseSelectLocalBasePosition
  relativeSplitFalseSelectLongExplicitSlot relativeSplitFalseSelectLongFlagBits
  relativeSplitFalseSelectLongCompactSlot relativeSplitFalseSelectSparseExplicitSlot
  relativeSplitFalseSelectSparseCompactSlot relativeSplitFalseSelectLocalSlotInSuper
  relativeSplitFalseSelectLocalSlot relativeOffsetReadCosted
  builtRelativeSplitSparseExceptionReadCosted
  builtRelativeSplitSparseExceptionReadCosted_cost_le_five
  builtRelativeSplitSparseExceptionReadCosted_erase
  builtRelativeSplitSparseExceptionReadCosted_lookup_exact
  builtRelativeSplitSparseExceptionNarrowReadCosted
  builtRelativeSplitSparseExceptionNarrowReadCosted_cost_le_five
  builtRelativeSplitSparseExceptionNarrowReadCosted_erase
  builtRelativeSplitSparseExceptionNarrowReadCosted_lookup_exact
  builtRelativeSplitFalseSelectSuperEntry_marked_eq_long
  builtRelativeSplitFalseSelectLocalEntry_marked_eq_flag
  builtRelativeSplitFalseSelectLocalBaseOccurrence_exact
  builtRelativeSplitFalseSelectLocalBasePosition_exact
  falseSelectOccurrenceCount_le_bpCode_length
  builtRelativeSplitFalseSelectPosition_le_length
  builtRelativeSplitFalseSelectPosition_lt_length_of_lt_count
  builtRelativeSplitFalseSelectSuperFieldWidth builtRelativeSplitFalseSelectLocalFieldWidth
  builtRelativeSplitFalseSelectSuperEntries_mem_fields_lt_width
  builtRelativeSplitFalseSelectSuperTable
  builtRelativeSplitFalseSelectSuperTable_payload_le_overhead
  builtRelativeSplitFalseSelectLocalEntries_mem_fields_lt_width
  builtRelativeSplitFalseSelectLocalTable
  builtRelativeSplitFalseSelectLocalTable_payload_le_overhead
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits_length_mul_wordBits_le
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagBits_length_le_overhead
  builtRelativeSplitFalseSelectSparseExceptionEffectiveFlagRankData_auxPayload_le_overhead
  sparseExceptionDirectoryOverhead sparseExceptionDirectoryOverhead_littleO
  canonicalSparseExceptionDirectoryOverhead
  canonicalSparseExceptionDirectoryOverhead_littleO fixedWidthNatTable_word_length_le_of_mem
  falseSelectCeilDiv_le_self_of_pos builtRelativeSplitFalseSelectLongSuperFlagBits_length
  builtRelativeSplitFalseSelectLongSuperFlagBits_length_le_bpCode_length
  builtRelativeSplitFalseSelectLongSuperFlagBits_length_mul_wordBits_le
  builtRelativeSplitFalseSelectLongSuperFlagBits_length_le_overhead
  builtRelativeSplitFalseSelectLongFlagRankWordSize_le_machine
  builtRelativeSplitFalseSelectLongFlagRankData_auxPayload_le_overhead
  builtRelativeSplitSparseExceptionFalseSelectCloseData
  builtRelativeSplitSparseExceptionFalseSelectCloseData_profile
  builtRelativeSplitFalseSelectLongSuperFlagBits_eq_relativeSplitLongFlagBits
  builtRelativeSplitFalseSelectSuperEntries_missing_exact
  builtRelativeSplitFalseSelectLongExplicit_exact falseSelectCeilDiv_mul_ge
  falseSelectLocalSlotsPerSuper_mul_localStride_ge_superStride nat_add_sub_one_le_mul_of_pos
  falseSelectLocalSlotsPerSuper_le_superStride builtRelativeSplitFalseSelectLocalSlot_facts
  builtRelativeSplitFalseSelectLocalEntries_missing_exact
  builtRelativeSplitSparseExceptionDirectory_readCosted_lookup_exact
  builtRelativeSplitFalseSelectSparseCompact_exact
  builtRelativeSplitFalseSelect_selected_lt_shortLocalBase_plus_span
  builtRelativeSplitFalseSelectDense_exact RelativeSplitSparseExceptionFalseSelectCloseData
  builtRectangularFalseSelectPaddedLocalCapacity_ge_size
  builtRectangularFalseSelectPaddedSuperCapacity_ge_size falseSelectRightSpine
  falseSelectRightSpine_shapeOfSize padded_relative_sparse_local_entries_not_littleO
  padded_relative_sparse_local_payload_not_littleO
  padded_relative_long_super_entries_not_littleO
  padded_relative_long_super_payload_not_littleO
  relativeSplitSparseException_long_super_padded_payload_not_littleO
  noRelativeSplitSparseExceptionFalseSelectCloseData_with_padded_long_super_payload
  noBuiltRelativeSplitSparseExceptionFalseSelectCloseData_with_current_long_slot_profile
  RelativeSplitSparseExceptionDirectory builtRelativeSplitSparseExceptionDirectory
  canonicalRelativeSplitSparseExceptionFalseSelectOverhead
  canonicalRelativeSplitSparseExceptionFalseSelectOverhead_littleO
  builtTwoLevelFalseSelectWordSize builtTwoLevelFalseSelectOccurrencesPerSuper
  builtTwoLevelFalseSelectWordSize_pos builtTwoLevelFalseSelectOccurrencesPerSuper_pos
  builtTwoLevelFalseSelect_bpCode_length_lt_word_pow builtTwoLevelFalseSelectSuperOverhead
  builtTwoLevelFalseSelectBlockOverhead
  builtTwoLevelFalseSelectBlockOverhead_ge_bpCode_length_succ
  builtTwoLevelFalseSelectSelectData TwoLevelFalseSelectCloseData
  builtTwoLevelFalseSelectCloseData builtTwoLevelFalseSelectCloseData_profile
  builtTwoLevelFalseSelectRightSpineBlockOverhead
  builtTwoLevelFalseSelectRightSpineBlockOverhead_ge_two_n_plus_one
  builtTwoLevelFalseSelect_current_finite_block_tables_not_littleO
  SparseDenseFalseSelectDenseLocalEntry
  sparseDenseFalseSelectDenseLocalEntryMultiwordPayloadBudget
  FixedWidthSparseDenseFalseSelectDenseLocalEntryTable fixedWidthLongSuperExplicitTable
  fixedWidthLongSuperExplicitTable_profile fixedWidthSparseLocalExplicitTable
  fixedWidthSparseLocalExplicitTable_profile sparseDenseFalseSelectOverhead
  sparseDenseFalseSelectOverhead_littleO SampledPayloadLiveStoredWordSelectData
  SampledPayloadLiveStoredWordSelectFamily ExactSampledPayloadLiveStoredWordSelectFamily
  selectLocatorPayloadBudget fixedWidthSelectSampleTables_payload_length_eq_budget
  fixedWidthSelectSampleTables_payload_length_le_sampled
  canonicalSelectBlockTablesFinite_payload_length_eq
  canonicalSelectBlockTablesFinite_payload_length_ge_succ not_littleOLinear_of_succ_le
  not_littleOLinear_of_self_le clarkSelectTwoWordDescriptorIndexIdentityOverhead
  clarkSelectTwoWordDescriptorIndexIdentityOverhead_ge_succ
  clarkSelectTwoWordDescriptorIndexIdentityOverhead_not_littleO
  canonicalSelectBlockTablesFinite_identity_payload_not_littleO
  noTwoLevelPayloadLiveStoredWordRankSelectFamily_with_canonical_select_block
  twoLevelBPCloseNavigationOverhead twoLevelBPCloseNavigationOverhead_littleO
  TwoLevelPayloadLiveBPCloseRMQNavigationDirectory
  TwoLevelPayloadLiveBPCloseRMQNavigationFamily TwoLevelEncodedBPCloseRMQNavigationView
  TwoLevelEncodedBPCloseRMQNavigationFamily clarkSelectChunkBase clarkSelectChunkOffset
  clarkSelectChunkBase_le clarkSelectChunkOffset_lt ClarkSelectChunkOneWord
  ClarkSelectTwoWordChunkCovers clarkSelectTwoWordChunk_descriptor_choice_exact
  clarkSelectTwoWordDescriptorSample clarkSelectTwoWordDescriptorSample_eq_selected
  clarkSelectTwoWordChunk_descriptor_sample_exact clarkSelectTwoWordDescriptorIndexOfPos
  clarkSelectTwoWordDescriptorIndexOfOccurrence clarkSelectTwoWordDescriptorIndexEntries
  clarkSelectTwoWordDescriptorIndexOfPos_covers ChargedSelectPositionSource
  chargedSelectPositionSource_allows_empty_select_oracle
  clarkSelectTwoWordDescriptorIndexEntries_mem_bound ClarkSelectTwoWordDescriptorIndexTable
  clarkSelectTwoWordDescriptorIndexTable clarkSelectTwoWordDescriptorIndexTable_read_covers
  clarkSelectTwoWordDescriptorIndexTable_profile
  clarkSelectTwoWordIdentityDescriptorRoute_profile
  clarkSelectTwoWordChunk_table_backed_sample_exact
  shared_descriptor_index_forces_same_two_word_run
  shared_descriptor_index_contradicts_distinct_two_word_run
  shared_descriptor_table_read_contradicts_distinct_two_word_run
  selectSampleOfSelectedPos_eq_of_same_wordIndex
  clarkSelectChunkBaseSample_exact_of_one_word clarkSelectChunk_payload_router_exact
  clarkSelectChunkBaseSample_exact_forces_same_wordIndex
  clarkSelectChunkBaseSample_cross_word_obstruction twoLevelRankSelectOverhead
  twoLevelRankSelectOverhead_littleO canonicalTwoLevelRankSelectOverhead
  canonicalTwoLevelRankSelectOverhead_littleO twoLevelRankSelectDirectory
  twoLevelRankSelectDirectory_profile canonicalTwoLevelRankSelectDirectoryOfChunksExact
  canonicalTwoLevelRankSelectDirectoryOfChunksExact_profile
  canonicalTwoLevelRankSelectDirectoryOfChunksExactLocalRankBlock
  canonicalTwoLevelRankSelectDirectoryOfChunksExactLocalRankBlock_profile
  canonicalTwoLevelBalancedParensAccessOfChunksExact
  canonicalTwoLevelBalancedParensAccessOfChunksExact_profile
  canonicalTwoLevelBalancedParensAccessOfChunksExactLocalRankBlock
  canonicalTwoLevelBalancedParensAccessOfChunksExactLocalRankBlock_profile
  TwoLevelPayloadLiveStoredWordRankSelectFamily TwoLevelPayloadLiveStoredWordSelectData
  canonicalTwoLevelSelectData canonicalTwoLevelSelectData_selectCosted_profile
  canonicalTwoLevelSelectDataOfLocal canonicalTwoLevelSelectDataOfLocal_selectCosted_profile
  canonicalTwoLevelSelectDataOfChunks
  canonicalTwoLevelSelectDataOfChunks_selectCosted_profile
  canonicalTwoLevelSelectDataOfChunksExact
  canonicalTwoLevelSelectDataOfChunksExact_selectCosted_profile
  TwoLevelPayloadLiveStoredWordSelectFamily twoLevelSelectOverhead
  twoLevelSelectOverhead_littleO canonicalTwoLevelSelectSuperOverhead
  canonicalTwoLevelSelectBlockOverhead canonicalTwoLevelSelectOverhead
  canonicalTwoLevelSelectSuperOverhead_littleO canonicalTwoLevelSelectBlockOverhead_littleO
  canonicalTwoLevelSelectOverhead_littleO addSelectSample selectWordStart
  selectSampleOfSelectedPos selectSampleAt? selectSampleAt?_none_exact
  selectSampleAt?_some_fields selectSampleOfSelectedPos_field_bounds
  selectSampleAt?_some_field_bounds selectSampleDelta addSelectSample_selectSampleDelta_eq
  selectSampleDelta_field_bounds_of_exact selectSuperOccurrence selectSuperSampleEntry?
  selectBlockDeltaEntry? selectSuperSampleEntries selectBlockDeltaEntries
  selectSuperSampleEntries_getOpt_exact selectBlockDeltaEntries_getOpt_exact
  selectSuperSampleEntries_present_of_lt selectBlockDeltaEntries_present_of_lt
  selectSuperSampleEntry?_some_field_bounds selectBlockDeltaEntry?_some_field_bounds
  selectSuperSampleEntries_mem_bound selectBlockDeltaEntries_mem_bound
  canonicalSelectSuperTables canonicalSelectBlockTables
  selectBlockDeltaEntry?_some_of_samples selectBlockDeltaEntry?_add_exact_of_le
  SelectSampleWordExact rankPrefix_take_length_eq rankPrefix_succ_of_select
  occurrence_lt_rankPrefix_of_select_lt rankPrefix_sub_le_span twoWordDescriptorChoice
  twoWordDescriptorWordIndex twoWordDescriptorBaseWordIndex twoWordDescriptorFirstCount
  twoWordDescriptorFirstCountEntries twoWordDescriptorFirstCount_le_wordSize
  twoWordDescriptorFirstCountEntries_getOpt_exact
  twoWordDescriptorFirstCountEntries_mem_bound twoWordDescriptorFirstCountTables
  twoWordDescriptorFirstCountTables_profile
  twoWordDescriptorWordIndex_exact_of_select_in_run
  twoWordDescriptorTableRead_choice_exact_of_select_in_run
  twoWordDescriptorWordIndex_exact_implies_position_in_run
  occurrencePairTwoWordDescriptorRouting_not_global
  occurrenceOnlyTwoWordDescriptorRouting_impossible
  coarseBaseTwoWordDescriptorRouting_not_global
  selectBlockDeltaEntry?_select_some_exact_of_word selectFrom_none_of_le_occurrence
  select_none_of_le_occurrence selectSampleAt?_none_exact_of_le
  selectSuperSampleEntry?_none_exact_of_occurrence
  selectBlockDeltaEntry?_some_fields_of_super selectBlockDeltaEntry?_none_exact_of_super
  canonicalSelectSuperCount canonicalSelectBlockCount canonicalSelectSuperTablesFinite
  canonicalSelectBlockTablesFinite canonicalSelectSuperTablesFinite_present
  canonicalSelectBlockTablesFinite_present canonicalSelectSuperTablesFinite_getOpt_exact
  canonicalSelectBlockTablesFinite_getOpt_exact selectFrom_index_mono select_index_mono
  select_index_strict_mono selectSampleAt?_sample_ordered_of_occurrence_le
  selectSuperSampleEntry?_sample_ordered CanonicalSelectWordBridge
  selectSampleAt?_word_present_ofChunks selectSampleAt?_word_eq_take_drop_ofChunks
  selectSampleAt?_slice_word_exact
)

namespace CanonicalSelectWordBridge

export SuccinctSelect.CanonicalSelectWordBridge (
  ofLocal ofChunks ofChunksSlice ofChunksExact
)

end CanonicalSelectWordBridge

namespace ChargedSelectPositionSource

export SuccinctSelect.ChargedSelectPositionSource (
  descriptorIndexCosted descriptorIndexCosted_cost_le descriptorIndexCosted_erase
  descriptorIndexCosted_covers descriptorIndexCosted_profile
  descriptorIndexCosted_table_backed_sample_exact ofTwoLevelSelectData
  ofTwoLevelSelectData_profile
)

end ChargedSelectPositionSource

namespace ClarkSelectTwoWordDescriptorIndexTable

export SuccinctSelect.ClarkSelectTwoWordDescriptorIndexTable (
  readCosted readCosted_cost_le_one readCosted_erase readCosted_covers profile
)

end ClarkSelectTwoWordDescriptorIndexTable

namespace ExactSampledPayloadLiveStoredWordSelectFamily

export SuccinctSelect.ExactSampledPayloadLiveStoredWordSelectFamily (
  toSampledFamily constant_query_profile bounded_constant_query_profile
)

end ExactSampledPayloadLiveStoredWordSelectFamily

namespace FixedWidthSparseDenseFalseSelectDenseLocalEntryTable

export SuccinctSelect.FixedWidthSparseDenseFalseSelectDenseLocalEntryTable (
  entryOfFields entryOfFields_get? payload readWords ofEntries readCosted
  readCosted_cost_le_four entry_fields_lt payload_length ReadProfile readProfile
  ReadWordsLengthLeMachine readWordsLengthLeMachine read_word_length_le_machine profile
  ofEntries_profile
)

end FixedWidthSparseDenseFalseSelectDenseLocalEntryTable

namespace RelativeSplitSparseExceptionDirectory

export SuccinctSelect.RelativeSplitSparseExceptionDirectory (
  payload payload_length_le_canonical readWords readCosted readCosted_cost_le_five
  readCosted_exact read_words_length_le_machine profile
)

end RelativeSplitSparseExceptionDirectory

namespace RelativeSplitSparseExceptionFalseSelectCloseData

export SuccinctSelect.RelativeSplitSparseExceptionFalseSelectCloseData (
  payload longFlagRankReadWords readWords queryOccurrence selectCloseCosted
  payload_length_le_canonical selectCloseCosted_cost_le selectCloseCosted_exact
  longFlagRank_read_word_length_le_machine read_word_length_le_machine profile
  toChargedSelectPositionSource relativeSplitDescriptorIndexCosted
  relativeSplitDescriptorIndexCosted_eq_chargedSource
  toChargedSelectPositionSource_descriptorIndexCosted_profile
  relativeSplitDescriptorIndexCosted_table_backed_sample_exact
  relativeSplitDescriptorIndexCosted_cost_le relativeSplitDescriptorIndexCosted_erase
  relativeSplitDescriptorIndexCosted_covers relativeSplitDescriptorIndexCosted_profile
  long_explicit_slot_lt_length_of_select
)

end RelativeSplitSparseExceptionFalseSelectCloseData

namespace SampledPayloadLiveStoredWordSelectData

export SuccinctSelect.SampledPayloadLiveStoredWordSelectData (
  auxPayload selectCosted auxPayload_length_le_sampled selectCosted_cost_le_three
  selectCosted_exact profile
)

end SampledPayloadLiveStoredWordSelectData

namespace SampledPayloadLiveStoredWordSelectFamily

export SuccinctSelect.SampledPayloadLiveStoredWordSelectFamily (
  bounded_constant_query_profile
)

end SampledPayloadLiveStoredWordSelectFamily

namespace SelectSampleWordExact

export SuccinctSelect.SelectSampleWordExact (
  exists_word_offset_of_select selected_position_in_read_word
  selected_wordIndex_eq_of_aligned_read_word shared_aligned_read_word_forces_same_wordIndex
)

end SelectSampleWordExact

namespace SparseDenseFalseSelectDenseLocalEntry

export SuccinctSelect.SparseDenseFalseSelectDenseLocalEntry (
  baseOccurrences baseWordIndices ranksBefore firstOffsets
)

end SparseDenseFalseSelectDenseLocalEntry

namespace TwoLevelEncodedBPCloseRMQNavigationFamily

export SuccinctSelect.TwoLevelEncodedBPCloseRMQNavigationFamily (
  overhead toBPCloseRMQNavigationFamily overhead_littleO Profile
  two_n_plus_o_encoded_query_profile
)

end TwoLevelEncodedBPCloseRMQNavigationFamily

namespace TwoLevelEncodedBPCloseRMQNavigationView

export SuccinctSelect.TwoLevelEncodedBPCloseRMQNavigationView (
  toBPCloseRMQNavigationDirectory
)

end TwoLevelEncodedBPCloseRMQNavigationView

namespace TwoLevelFalseSelectCloseData

export SuccinctSelect.TwoLevelFalseSelectCloseData (
  payload locatorReadWords readWords selectCloseCosted payload_length
  selectCloseCosted_cost_le selectCloseCosted_exact payload_word_length_le_machine profile
)

end TwoLevelFalseSelectCloseData

namespace TwoLevelPayloadLiveBPCloseRMQNavigationDirectory

export SuccinctSelect.TwoLevelPayloadLiveBPCloseRMQNavigationDirectory (
  overhead encodeAux payload selectCloseCosted lcaCloseCosted rankCloseCosted
  queryBuiltCosted encodeAux_length payload_length selectCloseCosted_cost_le
  lcaCloseCosted_cost_le_one rankCloseCosted_cost_le queryBuiltCosted_cost_le
  selectCloseCosted_exact rankCloseCosted_exact queryBuiltCosted_exact profile
)

end TwoLevelPayloadLiveBPCloseRMQNavigationDirectory

namespace TwoLevelPayloadLiveBPCloseRMQNavigationFamily

export SuccinctSelect.TwoLevelPayloadLiveBPCloseRMQNavigationFamily (
  overhead overhead_littleO two_n_plus_o_built_query_profile
)

end TwoLevelPayloadLiveBPCloseRMQNavigationFamily

namespace TwoLevelPayloadLiveStoredWordRankSelectFamily

export SuccinctSelect.TwoLevelPayloadLiveStoredWordRankSelectFamily (
  overhead overhead_littleO directory toRankSelectFamily toBitVectorRankSelectFamily
  constant_query_profile n_plus_o_constant_query_profile word_bounded_constant_query_profile
  word_bounded_n_plus_o_constant_query_profile toBalancedParensAccessFamily
  bp_constant_query_profile
)

end TwoLevelPayloadLiveStoredWordRankSelectFamily

namespace TwoLevelPayloadLiveStoredWordSelectData

export SuccinctSelect.TwoLevelPayloadLiveStoredWordSelectData (
  queryOccurrence superIndex superPayload blockPayload auxPayload selectCosted
  auxPayload_length payload_words_erase selectCosted_cost_le_four selectCosted_cost_le
  selectCosted_exact selected_position_in_read_word_of_sample
  selected_wordIndex_eq_of_sample shared_local_locator_forces_same_selected_wordIndex
  shared_local_locator_contradicts_distinct_selected_wordIndex
  payload_word_length_le_machine profile
)

end TwoLevelPayloadLiveStoredWordSelectData

namespace TwoLevelPayloadLiveStoredWordSelectFamily

export SuccinctSelect.TwoLevelPayloadLiveStoredWordSelectFamily (
  toChargedSelectPositionSource toChargedSelectPositionSource_profile overhead
  overhead_littleO constant_query_profile
)

end TwoLevelPayloadLiveStoredWordSelectFamily

end SuccinctSelectProposal
end RMQ
