import RMQ.Core.SuccinctRank

/-!
# Rank-side sampled-directory compatibility root

Compatibility import root for the old `RMQ.SuccinctRankProposal` namespace.
New code should import `RMQ.Core.SuccinctRank` and use `RMQ.SuccinctRank`.
-/

namespace RMQ
namespace SuccinctRankProposal

export SuccinctRank (
  machineWordBits machineWordBits_pos rankSampleEntries
  rankSampleEntries_getOpt_exact rankPrefix_mono_limit
  canonicalSuperRankEntries canonicalBlockRankEntries
  canonicalSuperRankEntries_getOpt_exact canonicalBlockRankEntries_getOpt_exact
  canonicalSuperRankEntries_present canonicalBlockRankEntries_present
  canonicalSuperRankEntries_mem_bound canonicalBlockRankEntries_mem_bound
  canonicalBlockRankEntries_mem_bound_of_local_span
  canonicalSuperRankSampleTables canonicalBlockRankSampleTables
  canonicalBlockRankSampleTablesOfLocalSpan
  canonicalSuperRankSampleTables_present canonicalBlockRankSampleTables_present
  canonicalBlockRankSampleTablesOfLocalSpan_present
  canonicalSuperRankSampleTables_payload_length
  canonicalBlockRankSampleTables_payload_length
  canonicalBlockRankSampleTablesOfLocalSpan_payload_length
  canonicalBlockRankSampleTablesOfLocalSpan_payload_eq
  canonicalSuperRankEntries_length canonicalBlockRankEntries_length
  canonicalRankParts_exact_of_word_local
  chunkPayloadWords_rankPrefix_exact ofChunks_rankPrefix_exact
  ofChunks_word_present_of_lt ofChunksWithSentinel_word_present
  ofChunksWithSentinel_rankPrefix_exact
  twoLevelRankOverhead twoLevelRankOverhead_littleO
  canonicalTwoLevelRankSuperOverhead canonicalTwoLevelRankBlockOverhead
  canonicalTwoLevelRankOverhead canonicalTwoLevelRankSuperOverhead_littleO
  canonicalTwoLevelRankBlockOverhead_littleO canonicalTwoLevelRankOverhead_littleO
  TwoLevelPayloadLiveStoredWordRankData CanonicalRankWordBridge
  canonicalRankWordBridgeOfChunks canonicalRankWordBridgeOfChunksWithSentinel
  canonicalTwoLevelRankDataOfBridge canonicalTwoLevelRankDataOfBridgeLocalBlock
  canonicalTwoLevelRankDataOfChunksPresent canonicalTwoLevelRankDataOfChunksPresentLocalBlock
  canonicalTwoLevelRankDataOfChunksExact canonicalTwoLevelRankDataOfChunksExactLocalBlock
  canonicalTwoLevelRankDataOfBridge_profile canonicalTwoLevelRankDataOfChunksExact_profile
  canonicalTwoLevelRankDataOfBridgeLocalBlock_profile
  canonicalTwoLevelRankDataOfChunksExactLocalBlock_profile
  jacobsonRankWordSize jacobsonRankBlocksPerSuper
  jacobsonRankSuperWidth jacobsonRankBlockWidth
  self_lt_two_pow_machineWordBits jacobsonRankBuilderSideConditions
  jacobsonRankSuperOverhead jacobsonRankBlockOverhead
  canonicalSuperRankSampleTables_payload_length_jacobson
  canonicalBlockRankSampleTablesOfLocalSpan_payload_length_jacobson
  machineWordBits_littleO nestedMachineWordBits_le_succ
  natLog2_le_log2_of_le machineWordBits_mono_le nestedMachineWordBits_littleO
  jacobsonRankSuperOverhead_le_envelope jacobsonRankSuperPayload_length_le_sampled
  jacobsonRankSuperOverhead_littleO machineWordBits_mul_self_log_bound
  machineWordBits_mul_self_littleO jacobsonRankBlockOverhead_le_envelope
  jacobsonRankBlockPayload_length_le_logLogSampled jacobsonRankBlockOverhead_littleO
  jacobsonRankOverhead jacobsonRankOverhead_littleO
  jacobsonRankData jacobsonRankData_profile
  TwoLevelPayloadLiveStoredWordRankFamily jacobsonRankFamily
  jacobsonRankFamily_constant_query_profile
  rankSamplePayloadBudget fixedWidthRankSampleTables_payload_length_eq_budget
  fixedWidthRankSampleTables_payload_length_le_sampled
  SampledPayloadLiveStoredWordRankData SampledPayloadLiveStoredWordRankFamily
  ExactSampledPayloadLiveStoredWordRankFamily
)

namespace TwoLevelPayloadLiveStoredWordRankData

export SuccinctRank.TwoLevelPayloadLiveStoredWordRankData (
  queryPos wordIndex superIndex wordOffset superPayload blockPayload auxPayload
  rankCosted auxPayload_length payload_words_erase rankCosted_cost_le_four
  rankCosted_cost_le rankCosted_exact payload_word_length_le_machine profile
)

end TwoLevelPayloadLiveStoredWordRankData

namespace TwoLevelPayloadLiveStoredWordRankFamily

export SuccinctRank.TwoLevelPayloadLiveStoredWordRankFamily (
  overhead overhead_littleO constant_query_profile
)

end TwoLevelPayloadLiveStoredWordRankFamily

namespace SampledPayloadLiveStoredWordRankData

export SuccinctRank.SampledPayloadLiveStoredWordRankData (
  auxPayload rankCosted auxPayload_length_le_sampled rankCosted_cost_le_three
  rankCosted_exact profile
)

end SampledPayloadLiveStoredWordRankData

namespace SampledPayloadLiveStoredWordRankFamily

export SuccinctRank.SampledPayloadLiveStoredWordRankFamily (
  bounded_constant_query_profile
)

end SampledPayloadLiveStoredWordRankFamily

namespace ExactSampledPayloadLiveStoredWordRankFamily

export SuccinctRank.ExactSampledPayloadLiveStoredWordRankFamily (
  toSampledFamily constant_query_profile bounded_constant_query_profile
)

end ExactSampledPayloadLiveStoredWordRankFamily

end SuccinctRankProposal
end RMQ