import RMQ
import RMQ.Core.SuccinctFinal

/-!
Checked archive trust-base inventory.

This file preserves axiom checks for superseded compatibility surfaces and
proof-obstruction results that are still useful to cite while the source is
being pruned. These theorems are no longer the public headline path, but the
gate still verifies that they do not depend on `sorryAx` or computational
trust-base shortcuts.
-/

/- BP-specialized sparse/dense false-select prototype and obstruction surface. -/

#print axioms RMQ.SuccinctSelectProposal.sparseDenseFalseSelectLocatorEntry_fullMachineField_not_word_bounded
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectLocatorEntryTable.ofEntries_profile
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectLocatorEntryTable.read_word_length_le_machine
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectLocatorEntryTable.profile
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectDenseLocalEntryTable.ofEntries_profile
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectDenseLocalEntryTable.readCosted_cost_le_four
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectDenseLocalEntryTable.readCosted_erase
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectDenseLocalEntryTable.readWordsLengthLeMachine
#print axioms RMQ.SuccinctSelectProposal.FixedWidthSparseDenseFalseSelectDenseLocalEntryTable.profile
#print axioms RMQ.SuccinctSelectProposal.builtLongExplicitFalseSelectBranch_long_explicit_exact
#print axioms RMQ.SuccinctSelectProposal.builtLongExplicitFalseSelectBranch_long_explicit_obligation
#print axioms RMQ.SuccinctSelectProposal.fixedWidthLongSuperExplicitTable_profile
#print axioms RMQ.SuccinctSelectProposal.fixedWidthSparseLocalExplicitTable_profile
#print axioms RMQ.SuccinctSelectProposal.sparseDenseFalseSelectOverhead_littleO
#print axioms RMQ.SuccinctSelectProposal.canonicalSparseDenseFalseSelectOverhead_littleO
#print axioms RMQ.SuccinctSelectProposal.denseTwoWordFalseSelectCosted_cost_le_five
#print axioms RMQ.SuccinctSelectProposal.denseLocalEntryFalseSelectCosted_cost_le_five
#print axioms RMQ.SuccinctSelectProposal.denseTwoWordFalseSelectCosted_exact_of_local_span
#print axioms RMQ.SuccinctSelectProposal.falseSelectDenseLocalSpanCertificate_of_payload_routing_facts
#print axioms RMQ.SuccinctSelectProposal.denseTwoWordFalseSelectCosted_exact_of_payload_routing_facts
#print axioms RMQ.SuccinctSelectProposal.sparseDenseFalseSelectBranchObligations_of_built_entries
#print axioms RMQ.SuccinctSelectProposal.sparseDenseFalseSelectBranchObligations_of_built_entries_and_dense_payload_facts
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCodecTables.payload_length
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCodecTables.readProfile
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCodecTables.readWordsLengthLeMachine
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCodecTables.profile_le_sparseDenseFalseSelectOverhead
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.payload_length_le_overhead
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.super_locator_entry_fields_lt
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.local_locator_entry_fields_lt
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.short_super_local_pointer_capacity_obstruction
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.dense_branch_packed_local_pointer_capacity_obstruction
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.super_locator_full_machine_field_impossible
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.local_locator_full_machine_field_impossible
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.selectCloseCosted_cost_le
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.selectCloseCosted_exact
#print axioms RMQ.SuccinctSelectProposal.SparseDenseFalseSelectCloseData.profile

/- BP-specialized relative-split false-select compatibility surface. -/

#print axioms RMQ.SuccinctSelectProposal.compactLongSuperFlagRank_eq_segmentIndex
#print axioms RMQ.SuccinctSelectProposal.compactLongSuperRelativeTable_lookup_exact
#print axioms RMQ.SuccinctSelectProposal.builtRelativeSplitFalseSelectLongSuperSpanSum_le_bpCode_length
#print axioms RMQ.SuccinctSelectProposal.compactLongSuperRelativeTable_payload_mul_ell_le_spanSum
#print axioms RMQ.SuccinctSelectProposal.compactLongSuperRelativeTable_payload_le_overhead
#print axioms RMQ.SuccinctSelectProposal.builtRelativeSplitFalseSelectSuperEntry_marked_eq_long
#print axioms RMQ.SuccinctSelectProposal.builtRelativeSplitFalseSelectLongExplicit_exact
#print axioms RMQ.SuccinctSelectProposal.builtRelativeSplitCompactLongSuperReadCosted_cost_le_five
#print axioms RMQ.SuccinctSelectProposal.builtRelativeSplitCompactLongSuperReadCosted_lookup_exact
#print axioms RMQ.SuccinctSelectProposal.RelativeSplitSparseExceptionFalseSelectCloseData.profile
#print axioms RMQ.SuccinctSelectProposal.RelativeSplitSparseExceptionFalseSelectCloseData.relativeSplitDescriptorIndexCosted_profile
#print axioms RMQ.SuccinctSelectProposal.RelativeSplitSparseExceptionFalseSelectCloseData.toChargedSelectPositionSource_descriptorIndexCosted_profile
#print axioms RMQ.SuccinctSelectProposal.RelativeSplitSparseExceptionFalseSelectCloseData.relativeSplitDescriptorIndexCosted_table_backed_sample_exact
#print axioms RMQ.SuccinctSelectProposal.builtRelativeSplitSparseExceptionFalseSelectCloseData_profile

/- Old close-access families preserved as checked compatibility surfaces. -/

#print axioms RMQ.SuccinctFinal.SparseDenseFalseSelectBPCloseAccessDirectory.selectCloseCosted_exact
#print axioms RMQ.SuccinctFinal.SparseDenseFalseSelectBPCloseAccessDirectory.rankCloseCosted_exact
#print axioms RMQ.SuccinctFinal.SparseDenseFalseSelectBPCloseAccessDirectory.profile
#print axioms RMQ.SuccinctFinal.SparseDenseFalseSelectBPCloseAccessFamily.constant_query_profile
#print axioms RMQ.SuccinctFinal.RelativeSplitSparseExceptionFalseSelectBPCloseAccessDirectory.profile
#print axioms RMQ.SuccinctFinal.RelativeSplitSparseExceptionFalseSelectBPCloseAccessFamily.constant_query_profile
#print axioms RMQ.SuccinctFinal.builtRelativeSplitSparseExceptionFalseSelectBPCloseAccessFamily_profile
#print axioms RMQ.SuccinctFinal.builtRelativeSplitSparseExceptionBPNativeSuccinctRMQFamily_two_n_plus_o_constant_query_profile
#print axioms RMQ.SuccinctFinal.builtRelativeSplitSparseExceptionBPNativeSuccinctRMQFamily_total_two_n_plus_o_constant_query_profile
#print axioms RMQ.SuccinctFinal.builtRelativeSplitSparseExceptionBPNativeSuccinctRMQFamily_total_two_sided_doubled_catalan_slack_profile
