import RMQPaper
import RMQ
import RMQ.Core.EncodingLowerBound
import RMQ.Headlines
import RMQ.Core.SuccinctFinal

/-!
Concise trust-base check for the public headline path.

The full `scripts/axiom_check.lean` is the acceptance gate. This smaller file
prints only the theorem surfaces most likely to appear in a public overview:
shared contract, RMQ/LCA reduction, lower bound, Fischer-Heun/LCA costs, and
the BP-native succinct capstone.
-/

#print axioms RMQ.RMQBackend.queryBuilt_eq
#print axioms RMQ.Cartesian.certifiedReduction
#print axioms RMQ.EncodingLowerBound.shapeCount_quadratic_lower
#print axioms RMQ.EncodingLowerBound.two_mul_sub_log_slack_le_bits_of_exactRMQShapeEncoding
#print axioms RMQ.EncodingLowerBound.exactRMQ_tight_fixed_length_payload_space_bound
#print axioms RMQ.Headlines.exactRMQLowerBoundDoubledCatalanSlack
#print axioms RMQ.FischerHeun.fischerHeun_refines_with_steps
#print axioms RMQ.LCAFischerHeun.denseLCA_linearBuild_constantQuery_profile
#print axioms RMQ.SuccinctClose.canonicalBPRelativeSummaryBlockSize_pos_of_size_ge
#print axioms RMQ.SuccinctClose.ConcreteCompactBPCloseLCADirectory.lcaCloseCostedWithRankSeed_eq_positive_dispatch_of_size_ge
#print axioms RMQ.SuccinctClose.ConcreteCompactBPCloseLCADirectory.lcaCloseCostedWithRankSeed_exact_of_query
#print axioms RMQ.SuccinctClose.ConcreteCompactBPCloseLCADirectory.lcaCloseCostedWithRankSeed_exact_of_query_of_size_ge
#print axioms RMQ.SuccinctFinal.builtGenericSparseExceptionSelectBPCloseAccessFamily_profile
#print axioms RMQ.Headlines.rankSelectNPlusOConstantQuery
#print axioms RMQ.Headlines.rankSelectWordBoundedNPlusOConstantQuery
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightConstantQuery
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightFamilyProfile
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightInterpretedFamilyProfile
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightGlobalPayloadStoreFusedProfile
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightGlobalPayloadStoreNoSyntheticFusedProfile
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightGlobalPayloadStoreExecutionStory
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightGlobalPayloadStoreBoundedExecutionStory
#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightTargetGlobalPayloadStoreBoundedExecutionStory
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQuery
#print axioms RMQ.Headlines.succinctRMQListIntTwoNPlusOConstantQuery
#print axioms RMQ.Headlines.listIntSuccinctRMQFlatPayloadStoreNoSyntheticExecutionStory
#print axioms RMQ.Headlines.listIntSuccinctRMQOccurrenceProvenanceOfValid
#print axioms RMQ.Headlines.listIntSuccinctRMQEventValueProducerProvenanceOfValid
#print axioms RMQ.Headlines.listIntSuccinctRMQPaperMainTheorem
#print axioms RMQ.Headlines.listIntSuccinctRMQQueryTraceResultWithStoreEqOfOrderedReadFootprint
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalWordsErasePublicPayload
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalFootprintRecorded
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalExecutionRefinesLogical
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalStoreAdapter
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalExecutionEqOfOrderedFootprint
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalValueFromSuppliedStore
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalValueDependency
#print axioms RMQ.Headlines.listIntSuccinctRMQReviewerPhysicalExecutionRefinesLogical
#print axioms RMQ.Headlines.listIntSuccinctRMQReviewerPhysicalExecutionEqOfOrderedFootprint
#print axioms RMQ.Headlines.succinctRMQProgramOccurrenceActualProducer
#print axioms RMQ.Headlines.succinctRMQProgramEventValueProducer
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalSourcesNodup
#print axioms RMQ.Headlines.succinctRMQReviewerSourceRegionInjective
#print axioms RMQ.Headlines.succinctRMQReviewerSegmentSourceCoverage
#print axioms RMQ.Headlines.succinctRMQReviewerEveryReadHasListedRegion
#print axioms RMQ.Headlines.succinctRMQReviewerEveryReadOccurrenceProvenance
#print axioms RMQ.Headlines.succinctRMQReviewerEveryReadEventValueProducerProvenance
#print axioms RMQ.Headlines.succinctRMQReviewerCountedSourceSuccessfulClosedValidOccurrence
#print axioms RMQ.Headlines.succinctRMQReviewerSharedBPConsumerSuccessfulClosedValidOccurrence
#print axioms RMQ.Headlines.succinctRMQReviewerSuccessfulOccurrenceImpliesOperationalProducer
#print axioms RMQ.Headlines.succinctRMQReviewerRepeatedEqualOccurrencesRemainDistinct
#print axioms RMQ.Headlines.succinctRMQReviewerCountedSourceComponentMayPath
#print axioms RMQ.Headlines.succinctRMQReviewerSharedBPConsumerComponentPath
#print axioms RMQ.Headlines.succinctRMQReviewerFreshUnusedSourceNoProducer
#print axioms RMQ.Headlines.succinctRMQReviewerPhysicalSourcesExcludeLegacyClose
#print axioms RMQ.Headlines.succinctRMQReviewerLegacyTailReadNone
#print axioms RMQ.Headlines.listIntSuccinctRMQQueryCostedInvalid
#print axioms RMQ.Headlines.listIntSuccinctRMQQueryCostedEmptyRange
#print axioms RMQ.Headlines.listIntSuccinctRMQQueryCostedReversedRange
#print axioms RMQ.Headlines.listIntSuccinctRMQQueryCostedOutOfBounds
#print axioms RMQ.Headlines.listIntSuccinctRMQRawAdequacyOfValid
#print axioms RMQ.Headlines.listIntSuccinctRMQInvalidPhysicalSemantics
#print axioms RMQ.Headlines.listIntSuccinctRMQPhysicalValueFromSuppliedStore
#print axioms RMQ.Headlines.listIntSuccinctRMQQueryCostedWithStoreEqQueryCostedOfFootprint
#print axioms RMQ.Headlines.listIntSuccinctRMQFinalFullModelSoundnessExactOfFootprintGlobal
#print axioms RMQ.Headlines.listIntSuccinctRMQFinalFullModelCostLeOfFootprintGlobal
#print axioms RMQ.Headlines.listIntSuccinctRMQCanonicalTransitionalFinalFullModelCostLeOfFootprintGlobal
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryInterpreted
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryLeafTrace
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryWordTrace
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryWordTraceLargeRegime
#print axioms RMQ.Headlines.succinctRMQGlobalPayloadStoreExecutionStory
#print axioms RMQ.Headlines.succinctRMQGlobalPayloadStoreExtensionalExecutionStory
#print axioms RMQ.Headlines.succinctRMQGlobalPayloadStoreBoundedExecutionStory
#print axioms RMQ.Headlines.succinctRMQGlobalPayloadStoreAllSizeStructuralExecutionStory
#print axioms RMQ.Headlines.succinctRMQGlobalPayloadStoreNoSyntheticExecutionStory
#print axioms RMQ.Headlines.succinctRMQFlatPayloadStoreNoSyntheticExecutionStory
#print axioms RMQ.Headlines.succinctRMQFinalTraceModelAdequacy
#print axioms RMQ.Headlines.succinctRMQReviewerManifestSemanticAdequacy
#print axioms RMQ.Headlines.succinctRMQFinalTraceModelAdequacyExact
#print axioms RMQ.Headlines.succinctRMQFinalSuppliedStoreAdequacy
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceResultWithStoreReadsSubsetFootprint
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceResultReadsSubsetFootprint
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceResultWithStoreEqGlobalOfFootprint
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceResultWithStoreSuccessfulReadsBackedByCanonicalReviewerPayloadOfFootprintGlobal
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceCanonicalTransitionalCostedCostLe
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceCostedCostLe
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceCostedWithStoreCostLeOfFootprintGlobal
#print axioms RMQ.Headlines.succinctRMQQueryCostEq
#print axioms RMQ.Headlines.succinctRMQCompatibility4144QueryCostEq
#print axioms RMQ.Headlines.succinctRMQLegacy196727QueryCostEq
#print axioms RMQ.Headlines.succinctRMQCanonicalTransitionalQueryCostEq
#print axioms RMQ.Headlines.succinctRMQWholeQueryGlobalWordTraceCostedWithStoreExactOfFootprintGlobal
#print axioms RMQ.Headlines.succinctRMQFinalFullModelSoundness
#print axioms RMQ.Headlines.succinctRMQFinalFullModelSoundnessExactOfFootprintGlobal
#print axioms RMQ.Headlines.succinctRMQCanonicalTransitionalFinalFullModelCostLeOfFootprintGlobal
#print axioms RMQ.Headlines.succinctRMQLargeRegimeGlobalPayloadStoreExecutionStory
#print axioms RMQ.Headlines.succinctRMQLargeRegimeGlobalPayloadStoreBoundedExecutionStory
#print axioms RMQ.Headlines.concreteBPCloseNavigationProfile
#print axioms RMQ.Headlines.concreteBPCloseNavigationGlobalPayloadStoreExecutionStory
#print axioms RMQ.Headlines.concreteBPCloseNavigationGlobalPayloadStoreBoundedExecutionStory
#print axioms RMQ.Headlines.concreteSuccinctBPTreeNavigationGlobalPayloadStoreBoundedExecutionStory_currentCloseStoreObstruction
#print axioms RMQ.Headlines.bpCloseNavigationInterpretedTwoNPlusOConstantQuery
