import RMQRankSelect

/-!
Focused trust-base check for the standalone rank/select spoke.

The full RMQ gate still runs `scripts/axiom_check.lean`.  This smaller check is
for the reusable rank/select spoke: stored-bit access, Jacobson rank,
Clark-style sparse-exception select, `n + o(n)` auxiliary payload, the
fixed-weight compressed/FID codec spine, the compressed directory/family theorem
shape, and the charged local table/RAM block scaffolding.
-/

#print axioms RMQ.RankSelectSpec.BitVectorRankSelectFamily.n_plus_o_constant_query_profile
#print axioms RMQ.RankSelectSpec.fixedWeightBitstrings_length
#print axioms RMQ.RankSelectSpec.fixedWeightBitstrings_mem_length_trueCount
#print axioms RMQ.RankSelectSpec.fixedWeightBitstrings_mem_of_length_trueCount
#print axioms RMQ.RankSelectSpec.fixedWeightBitstrings_mem_iff
#print axioms RMQ.RankSelectSpec.fixedWeightBitstrings_nodup
#print axioms RMQ.RankSelectSpec.fixedWeightCodec_roundTrip
#print axioms RMQ.RankSelectSpec.fixedWeightEncode?_lt_binomialCount
#print axioms RMQ.RankSelectSpec.fixedWeightEncode?_eq_some_fixedWeightCode
#print axioms RMQ.RankSelectSpec.fixedWeightCode_lt_binomialCount
#print axioms RMQ.RankSelectSpec.fixedWeightEncode?_lt_payloadBudgetPow
#print axioms RMQ.RankSelectSpec.fixedWeightCode_lt_payloadBudgetPow
#print axioms RMQ.RankSelectSpec.fixedWeightPackedPayload_length
#print axioms RMQ.RankSelectSpec.fixedWeightPackedPayload_bitsToNatLE
#print axioms RMQ.RankSelectSpec.fixedWeightDecode?_packedPayload
#print axioms RMQ.RankSelectSpec.fixedWeightPackedPayload_profile
#print axioms RMQ.RankSelectSpec.fixedWeightPackedReadbackDirectory_profile
#print axioms RMQ.RankSelectSpec.FixedWeightPackedReadbackData.profile
#print axioms RMQ.RankSelectSpec.FixedWeightPackedReadbackData.ofChunks_profile
#print axioms RMQ.RankSelectSpec.boundedPayloadWordReadsCosted_cost
#print axioms RMQ.RankSelectSpec.boundedPayloadWordReadsCosted_erase
#print axioms RMQ.RankSelectSpec.dependentPayloadWordReadsCosted_cost
#print axioms RMQ.RankSelectSpec.dependentPayloadWordReadsCosted_erase
#print axioms RMQ.RankSelect.fixedWeightAuxiliaryWordReadsCostedCost
#print axioms RMQ.RankSelect.fixedWeightAuxiliaryWordReadsCostedErase
#print axioms RMQ.RankSelect.fixedWeightDependentAuxiliaryWordReadsCostedCost
#print axioms RMQ.RankSelect.fixedWeightDependentAuxiliaryWordReadsCostedErase
#print axioms RMQ.RankSelectSpec.FixedWeightCompressedAuxiliaryData.directory_profile
#print axioms RMQ.RankSelectSpec.FixedWeightDependentAuxiliaryData.directory_profile
#print axioms RMQ.RankSelect.fixedWeightDependentAuxiliaryDataProfile
#print axioms RMQ.RankSelectSpec.fixedWeightBlockCodePayload_length
#print axioms RMQ.RankSelectSpec.fixedWeightBlockCodeBoundedStore_words_toList
#print axioms RMQ.RankSelectSpec.fixedWeightAmbientBlockCodeStore_get?_of_aligned
#print axioms RMQ.RankSelectSpec.fixedWeightBlockCodeBoundedStore_get?_of_block
#print axioms RMQ.RankSelectSpec.fixedWeightAmbientBlockAuxiliaryOverhead_littleO
#print axioms RMQ.RankSelect.fixedWeightAmbientBlockAuxiliaryOverheadLittleO
#print axioms RMQ.RankSelectSpec.FixedWeightAmbientBlockCompositionData.directory_profile
#print axioms RMQ.RankSelect.fixedWeightAmbientBlockCompositionDataProfile
#print axioms RMQ.RankSelectSpec.FixedWeightAmbientBlockCompositionData.word_bounded_directory_profile
#print axioms RMQ.RankSelect.fixedWeightAmbientBlockCompositionWordBoundedDataProfile
#print axioms RMQ.RankSelectSpec.FixedWeightAmbientBlockCompositionFamily.ambient_block_composition_profile
#print axioms RMQ.RankSelect.fixedWeightAmbientBlockCompositionFamilyProfile
#print axioms RMQ.RankSelectSpec.FixedWeightAmbientBlockCompositionFamily.word_bounded_profile
#print axioms RMQ.RankSelect.fixedWeightAmbientBlockCompositionFamilyWordBoundedProfile
#print axioms RMQ.RankSelectSpec.FixedWeightAmbientBlockCompositionFamily.compressed_profile_of_primary_budget
#print axioms RMQ.RankSelect.fixedWeightAmbientBlockCompositionCompressedProfileOfPrimaryBudget
#print axioms RMQ.RankSelectSpec.FixedWeightCompressedAuxiliaryFamily.constant_query_profile
#print axioms RMQ.RankSelectSpec.FixedWeightCompressedAuxiliaryFamily.toCompressedFamily_fixed_weight_constant_query_profile
#print axioms RMQ.RankSelect.compressedDirectoryProfile
#print axioms RMQ.RankSelect.fixedWeightCompressedAuxiliaryConstantQueryProfile
#print axioms RMQ.RankSelect.fixedWeightCompressedAuxiliaryToCompressedFamilyProfile
#print axioms RMQ.RankSelectSpec.FixedWeightTableBackedFIDData.directory_profile
#print axioms RMQ.RankSelect.fixedWeightTableBackedFIDDataProfile
#print axioms RMQ.RankSelectSpec.fixedWeightDecodedWordTablePayload_length
#print axioms RMQ.RankSelectSpec.fixedWeightDecodedWordBoundedStore_get?_of_decode
#print axioms RMQ.RankSelectSpec.fixedWeightDecodedWordBoundedStore_get?_fixedWeightCode
#print axioms RMQ.RankSelect.fixedWeightDecodedWordBoundedStoreGetFixedWeightCode
#print axioms RMQ.RankSelectSpec.fixedWeightPackedCodeBoundedStore_get?_zero
#print axioms RMQ.RankSelect.fixedWeightPackedCodeBoundedStoreGetZero
#print axioms RMQ.RankSelectSpec.FixedWeightTableRAMBlockData.decodedTableOverhead_eq
#print axioms RMQ.RankSelectSpec.FixedWeightTableRAMBlockData.directory_profile
#print axioms RMQ.RankSelect.fixedWeightTableRAMBlockDataProfile
#print axioms RMQ.RankSelect.fixedWeightTableRAMBlockDependentAuxiliaryDataProfile
#print axioms RMQ.RankSelectSpec.FixedWeightTableRAMBlockData.dependent_auxiliary_bridge_profile
#print axioms RMQ.RankSelect.fixedWeightTableRAMBlockDependentAuxiliaryBridgeProfile
#print axioms RMQ.RankSelect.fixedWeightTableRAMBlockDependentAuxiliaryFullProfile
#print axioms RMQ.RankSelectSpec.FixedWeightTableRAMBlockData.dependent_read_profile
#print axioms RMQ.RankSelect.fixedWeightTableRAMBlockDependentReadProfile
#print axioms RMQ.RankSelectSpec.fixedWeightEncode?_fixedWeightDecode?
#print axioms RMQ.RankSelectSpec.fixedWeightDecode?_eq_some_iff
#print axioms RMQ.RankSelectSpec.fixedWeightDecode?_mem_length_trueCount
#print axioms RMQ.RankSelectSpec.CompressedBitVectorRankSelectDirectory.profile
#print axioms RMQ.RankSelectSpec.CompressedBitVectorRankSelectFamily.fixed_weight_constant_query_profile
#print axioms RMQ.RankSelect.compressedFixedWeightConstantQueryProfile
#print axioms RMQ.RankSelect.jacobsonClarkNPlusOConstantQuery
#print axioms RMQ.RankSelect.jacobsonClarkWordBoundedNPlusOConstantQuery
#print axioms RMQ.GenericSelect.sparseExceptionSelectSource_profile
#print axioms RMQ.GenericSelect.jacobsonClarkRankSelectOverhead_littleO
#print axioms RMQ.GenericSelect.jacobsonClarkRankSelectFamily_n_plus_o_constant_query_profile
#print axioms RMQ.GenericSelect.jacobsonClarkRankSelectFamily_word_bounded_n_plus_o_constant_query_profile
