import RMQ.Headlines
import RMQ.Core.SuccinctSpace.BPCloseLCARegisterRAM

/-!
Focused trust-base check for the Word-RAM refinement boundary.

This is intentionally smaller than `scripts/axiom_check.lean`: it checks the
first-order interpreter provenance lemmas and the public interpreted capstones
that consume the Word-RAM bridge layer.
-/

#print axioms RMQ.WordRAM.Program.eval_toCosted_cost_eq_trace_length
#print axioms RMQ.WordRAM.Program.eval_reads_subset_payload
#print axioms RMQ.WordRAM.Program.eval_readWord_event_eq_store
#print axioms RMQ.WordRAM.Program.eval_word_reads_length_le_machine
#print axioms RMQ.WordRAM.Program.eval_eq_of_readWord_eq
#print axioms RMQ.WordRAM.Program.eval_toCosted_eq_of_readWord_eq
#print axioms RMQ.WordRAM.TraceResult.costOnlyTrace_no_readWord
#print axioms RMQ.WordRAM.TraceResult.ofCosted_trace_no_readWord

#print axioms RMQ.WordRAM.Register.RegProgram.eval_toCosted_cost_eq_trace_length
#print axioms RMQ.WordRAM.Register.RegProgram.eval_reads_subset_payload
#print axioms RMQ.WordRAM.Register.RegProgram.eval_readWord_event_eq_store
#print axioms RMQ.WordRAM.Register.RegProgram.eval_word_reads_length_le_machine
#print axioms RMQ.WordRAM.Register.RegProgram.eval_eq_of_readWord_eq
#print axioms RMQ.WordRAM.Register.RegProgram.eval_toCosted_eq_of_readWord_eq
#print axioms RMQ.WordRAM.Register.RegProgram.eval_trace_length_le_readCount

#print axioms RMQ.WordRAM.Register.NatProgram.eval_toCosted_cost_eq_trace_length
#print axioms RMQ.WordRAM.Register.NatProgram.eval_reads_subset_payload
#print axioms RMQ.WordRAM.Register.NatProgram.eval_readWord_event_eq_store
#print axioms RMQ.WordRAM.Register.NatProgram.eval_word_reads_length_le_machine
#print axioms RMQ.WordRAM.Register.NatProgram.eval_eq_of_readWord_eq
#print axioms RMQ.WordRAM.Register.NatProgram.eval_toCosted_eq_of_readWord_eq
#print axioms RMQ.WordRAM.Register.NatProgram.eval_trace_length_le_stepCount

#print axioms RMQ.SuccinctSpace.PayloadLiveBPCloseLCADirectory.lcaCloseFromEndpointRegsProgram_refines_lcaCloseProgram_glue
#print axioms RMQ.SuccinctSpace.PayloadLiveBPCloseLCADirectory.lcaCloseFromEndpointRegsProgram_cost_le_one
#print axioms RMQ.SuccinctSpace.PayloadLiveBPCloseLCADirectory.lcaCloseFromEndpointRegsProgram_reads_subset_payload

#print axioms RMQ.SuccinctSpace.PayloadLiveStoredWordRankData.rankRegProgram_refines_rankCostedClamped
#print axioms RMQ.SuccinctSpace.PayloadLiveStoredWordRankData.rankRegProgram_exact
#print axioms RMQ.SuccinctRank.TwoLevelPayloadLiveStoredWordRankData.rankRegisterProgram_refines_rankInterpretedCosted
#print axioms RMQ.SuccinctRank.TwoLevelPayloadLiveStoredWordRankData.rankRegisterInterpretedCosted_refines_rankInterpretedCosted
#print axioms RMQ.SuccinctRank.TwoLevelPayloadLiveStoredWordRankData.rankRegisterInterpretedCosted_exact
#print axioms RMQ.GenericSelect.SparseExceptionSelectData.selectTraceResult_refines_interpretedCosted
#print axioms RMQ.SuccinctClose.bpTwoLevelInteriorCandidateTraceResultAtSegments_refines
#print axioms RMQ.SuccinctClose.ConcreteCompactBPCloseLCADirectory.lcaCloseTraceResultWithRankSeedAtSegmentsOfSizeGe_refines
#print axioms RMQ.SuccinctClose.ConcreteCompactBPCloseLCADirectory.lcaCloseTraceResultWithRankSeed_refines
#print axioms RMQ.SuccinctFinal.concreteBPNativeLCACloseWordTraceResult_refines_interpretedCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeLCACloseWordTraceResultAtSegmentsOfSizeGe_refines_interpretedCosted

#print axioms RMQ.RankSelectSpec.subLogAccessInterpretedCosted_refines_subLogAccessCosted
#print axioms RMQ.RankSelectSpec.subLogRankInterpretedCosted_refines_subLogRankCosted
#print axioms RMQ.RankSelectSpec.subLogSelectFromPackedClarkRouteInterpretedCosted_refines
#print axioms RMQ.RankSelect.compressedFIDFixedWeightInterpretedFamilyProfile

#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQQueryInterpretedCosted_refines_queryCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQQueryInterpretedCosted_exact
#print axioms RMQ.SuccinctFinal.builtGenericSparseExceptionBPNativeSuccinctRMQFamily_total_two_sided_doubled_catalan_slack_interpreted_profile
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryInterpretedCosted_refines_queryInterpretedCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryInterpretedCosted_exact
#print axioms RMQ.SuccinctFinal.builtGenericSparseExceptionBPNativeSuccinctRMQFamily_total_two_sided_doubled_catalan_slack_whole_query_interpreted_profile
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryLeafTraceCosted_refines_wholeQueryInterpretedCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryLeafTraceCosted_exact
#print axioms RMQ.SuccinctFinal.builtGenericSparseExceptionBPNativeSuccinctRMQFamily_total_two_sided_doubled_catalan_slack_whole_query_leaf_trace_profile
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryWordTraceCosted_refines_wholeQueryInterpretedCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryWordTraceCosted_exact
#print axioms RMQ.SuccinctFinal.builtGenericSparseExceptionBPNativeSuccinctRMQFamily_total_two_sided_doubled_catalan_slack_whole_query_word_trace_profile
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTraceCosted_refines_wholeQueryInterpretedCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTraceResult_matchesReadStore
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTrace_execution_story
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTraceCosted_exact
#print axioms RMQ.SuccinctClassic.listInt_two_n_plus_o_constant_query_profile
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryWordTraceCostedOfSizeGe_refines_wholeQueryInterpretedCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryWordTraceCostedOfSizeGe_eq_traceResult_toCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryWordTraceResultOfSizeGe_event_admissible
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryWordTraceCostedOfSizeGe_exact
#print axioms RMQ.SuccinctFinal.builtGenericSparseExceptionBPNativeSuccinctRMQFamily_total_two_sided_doubled_catalan_slack_whole_query_word_trace_large_regime_profile
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTraceCostedOfSizeGe_refines_wholeQueryInterpretedCosted
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTraceResultOfSizeGe_matchesReadStore
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTraceOfSizeGe_execution_story
#print axioms RMQ.SuccinctFinal.concreteBPNativeSuccinctRMQWholeQueryGlobalWordTraceCostedOfSizeGe_exact
#print axioms RMQ.SuccinctFinal.builtGenericSparseExceptionBPNativeSuccinctRMQFamily_total_two_sided_doubled_catalan_slack_whole_query_global_word_trace_large_regime_profile

#print axioms RMQ.Headlines.rankSelectCompressedFIDFixedWeightInterpretedFamilyProfile
#print axioms RMQ.Headlines.succinctRMQListIntTwoNPlusOConstantQuery
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryInterpreted
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryLeafTrace
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryWordTrace
#print axioms RMQ.Headlines.succinctRMQTwoNPlusOConstantQueryWordTraceLargeRegime
#print axioms RMQ.Headlines.succinctRMQGlobalPayloadStoreExecutionStory
#print axioms RMQ.Headlines.succinctRMQLargeRegimeGlobalPayloadStoreExecutionStory
