[package]
name = "packed-rmq"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "packed-rmq-route"
path = "src/main.rs"

[[bin]]
name = "packed-rmq-native"
path = "src/native_main.rs"

[[bin]]
name = "packed-rmq-lifecycle"
path = "src/lifecycle_main.rs"

[[test]]
name = "lifecycle_rust"
path = "tests/lifecycle_rust.rs"
harness = false
